import React from "react";
import {
  Briefcase,
  Code,
  Compass,
  HeartPulse,
  LineChart,
  Lightbulb,
  Scale,
  Video,
  TrendingUp,
  Calculator,
  Building2,
  Brain,
  Cpu,
  Shield,
  Cloud,
  Palette,
  Film,
  Smile,
  Activity,
  DollarSign,
  BarChart2,
  Landmark,
  Star,
  HardHat,
  Settings,
  Users2,
  Megaphone,
  UserCheck,
  Plane,
  Scissors,
  Camera,
  CalendarDays,
  Hotel,
  Heart,
  BookOpen,
  Monitor,
  Newspaper,
  MessageSquare,
  Apple,
  Dumbbell,
  Gamepad2,
  Link2,
  Leaf,
  FlaskConical,
  Truck,
  Layers,
  PieChart,
  Pill,
  GraduationCap,
  Globe,
  Music,
  PenTool,
  Stethoscope,
  Terminal,
} from "lucide-react";

export const ICON_OPTIONS = [
  { name: "Code", icon: Code, label: "Coding / Tech" },
  { name: "Cpu", icon: Cpu, label: "Hardware / AI" },
  { name: "Terminal", icon: Terminal, label: "Development" },
  { name: "Briefcase", icon: Briefcase, label: "Business / Corporate" },
  { name: "HeartPulse", icon: HeartPulse, label: "Healthcare / Medical" },
  { name: "Stethoscope", icon: Stethoscope, label: "Doctor / Medicine" },
  { name: "Scale", icon: Scale, label: "Law / Justice" },
  { name: "Lightbulb", icon: Lightbulb, label: "Innovation / Startup" },
  { name: "Palette", icon: Palette, label: "Design / Creative" },
  { name: "PenTool", icon: PenTool, label: "Art / Illustration" },
  { name: "Video", icon: Video, label: "Media / Video" },
  { name: "Camera", icon: Camera, label: "Photography" },
  { name: "Film", icon: Film, label: "Film / Cinema" },
  { name: "Music", icon: Music, label: "Music / Audio" },
  { name: "BarChart2", icon: BarChart2, label: "Data / Analytics" },
  { name: "LineChart", icon: LineChart, label: "Finance / Stocks" },
  { name: "Calculator", icon: Calculator, label: "Accounting / Math" },
  { name: "Building2", icon: Building2, label: "Real Estate / Architecture" },
  { name: "HardHat", icon: HardHat, label: "Engineering / Construction" },
  { name: "GraduationCap", icon: GraduationCap, label: "Education / Academic" },
  { name: "BookOpen", icon: BookOpen, label: "Literature / Research" },
  { name: "FlaskConical", icon: FlaskConical, label: "Science / Chemistry" },
  { name: "Leaf", icon: Leaf, label: "Biology / Environment" },
  { name: "Globe", icon: Globe, label: "International / Travel" },
  { name: "Plane", icon: Plane, label: "Aviation" },
  { name: "Megaphone", icon: Megaphone, label: "Marketing / PR" },
  { name: "Users2", icon: Users2, label: "HR / People" },
  { name: "Shield", icon: Shield, label: "Security / Defense" },
  { name: "Cloud", icon: Cloud, label: "Cloud / DevOps" },
  { name: "Gamepad2", icon: Gamepad2, label: "Gaming" },
  { name: "Lightbulb", icon: Lightbulb, label: "Emerging / General" },
];

export const ICON_MAP = {
  Briefcase,
  Code,
  Compass,
  HeartPulse,
  LineChart,
  Lightbulb,
  Scale,
  Video,
  TrendingUp,
  Calculator,
  Building2,
  Brain,
  Cpu,
  Shield,
  Cloud,
  Palette,
  Film,
  Smile,
  Activity,
  DollarSign,
  BarChart2,
  Landmark,
  Star,
  HardHat,
  Settings,
  Users2,
  Megaphone,
  UserCheck,
  Plane,
  Scissors,
  Camera,
  CalendarDays,
  Hotel,
  Heart,
  BookOpen,
  Monitor,
  Newspaper,
  MessageSquare,
  Apple,
  Dumbbell,
  Gamepad2,
  Link2,
  Leaf,
  FlaskConical,
  Truck,
  Layers,
  PieChart,
  Pill,
  Sparkles: Lightbulb,
  GraduationCap,
  Globe,
  Music,
  PenTool,
  Stethoscope,
  Terminal,
};

export function CareerIcon({ icon, size = 22, className = "" }) {
  if (!icon) {
    return <Briefcase size={size} className={className} />;
  }

  // If already a component/function
  if (typeof icon === "function" || (typeof icon === "object" && icon.$$typeof)) {
    const IconComponent = icon;
    return <IconComponent size={size} className={className} />;
  }

  // If icon is a string identifier
  if (typeof icon === "string") {
    const IconComponent = ICON_MAP[icon] || Briefcase;
    return <IconComponent size={size} className={className} />;
  }

  return <Briefcase size={size} className={className} />;
}
