/**
 * Centralized Career Assessment Configuration for Growvia
 * Standardized across 10 core career dimensions and mapped directly
 * to available database roadmaps with family-aware diversity classification.
 */

// 1. The 10 Core Career Dimensions (0–100 normalized score)
export const DIMENSION_KEYS = [
  "technical",
  "analytical",
  "creative",
  "business",
  "communication",
  "leadership",
  "research",
  "people",
  "structured",
  "riskTaking",
];

export const DIMENSION_LABELS = {
  technical: "Technical & Systems",
  analytical: "Analytical & Logic",
  creative: "Creative & Design",
  business: "Business & Strategy",
  communication: "Communication & Expression",
  leadership: "Leadership & Initiative",
  research: "Research & Investigation",
  people: "People & Empathy",
  structured: "Structure & Process",
  riskTaking: "Innovation & Risk Tolerance",
};

export const DIMENSION_DESCRIPTIONS = {
  technical: "Aptitude for coding, software architecture, infrastructure, and engineering mechanisms.",
  analytical: "Strength in quantitative logic, data analysis, pattern recognition, and mathematical deduction.",
  creative: "Intuition for aesthetic design, visual storytelling, artistic expression, and divergent thinking.",
  business: "Acumen for market dynamics, commercial growth, financial modeling, and strategic ROI.",
  communication: "Fluency in articulating concepts, stakeholder persuasion, writing, and presentation.",
  leadership: "Ability to inspire teams, steer roadmap vision, take ownership, and drive execution.",
  research: "Dedication to methodical exploration, literature synthesis, hypothesis testing, and deep inquiry.",
  people: "Empathy, active listening, psychological insight, mentorship, and service to others.",
  structured: "Affinity for systematic workflows, meticulous compliance, discipline, and order.",
  riskTaking: "Comfort with ambiguity, experimentation, unmapped territories, and entrepreneurial risk.",
};

// Relative dimension importance weights for similarity scoring
export const DIMENSION_WEIGHTS = {
  technical: 1.15,
  analytical: 1.20,
  creative: 1.05,
  business: 1.10,
  communication: 1.05,
  leadership: 1.00,
  research: 1.00,
  people: 0.95,
  structured: 0.90,
  riskTaking: 0.85,
};

// 2. Primary Career Families for Diversity-Aware Filtering
export const CAREER_FAMILIES = {
  technology: "Technology & Software",
  data: "Data & AI",
  design: "Design & Creative",
  business: "Business & Management",
  marketing: "Marketing & Growth",
  finance: "Finance & Accounting",
  healthcare: "Healthcare & Medicine",
  legal: "Law & Governance",
  media: "Media & Communication",
  engineering: "Core Engineering",
  education: "Education & Training",
  social: "Social Sciences & Welfare",
  science: "Science & Environment",
  operations: "Operations & Logistics",
  wellness: "Health & Wellness",
  hospitality: "Hospitality & Aviation",
};

// 3. 10 High-Quality Questions identifying preferences, strengths, motivations, and styles
export const QUIZ_QUESTIONS = [
  {
    id: "q1",
    category: "Problem Solving",
    question: "When faced with a complex, high-stakes challenge, which approach sounds most satisfying?",
    type: "single",
    description: "Your default problem-solving reflex under demanding conditions.",
    options: [
      {
        id: "q1_opt1",
        title: "Architecting a technical system or building a functional prototype to fix it",
        desc: "Designing logic, assembling digital mechanisms, and delivering a tangible technical solution.",
        dimensions: { technical: 5, analytical: 3, structured: 3, creative: 1 },
      },
      {
        id: "q1_opt2",
        title: "Analyzing underlying data, isolating patterns, and modeling root causes",
        desc: "Investigating datasets, calculating trends, and establishing empirical evidence before acting.",
        dimensions: { analytical: 5, research: 4, structured: 3, technical: 2 },
      },
      {
        id: "q1_opt3",
        title: "Designing an intuitive, creative approach that reimagines the user experience",
        desc: "Creating aesthetic, human-friendly solutions that delight users and stand out visually.",
        dimensions: { creative: 5, people: 3, communication: 2, riskTaking: 2 },
      },
      {
        id: "q1_opt4",
        title: "Aligning stakeholders, organizing resources, and negotiating a strategic solution",
        desc: "Uniting people, setting organizational priorities, and navigating commercial outcomes.",
        dimensions: { leadership: 5, business: 4, communication: 4, people: 3 },
      },
    ],
  },
  {
    id: "q2",
    category: "Work Preference",
    question: "Which type of challenge would you most enjoy immersing yourself in for several hours?",
    type: "single",
    description: "The domain of deep work where you naturally experience peak focus.",
    options: [
      {
        id: "q2_opt1",
        title: "Writing code, configuring systems, or debugging intricate workflows",
        desc: "Continuous technical focus on algorithms, codebases, or complex infrastructure.",
        dimensions: { technical: 5, structured: 4, analytical: 3, research: 1 },
      },
      {
        id: "q2_opt2",
        title: "Exploring scientific literature, investigating theories, or running experiments",
        desc: "Methodological research, hypothesis validation, and uncovering core insights.",
        dimensions: { research: 5, analytical: 4, creative: 2, structured: 2 },
      },
      {
        id: "q2_opt3",
        title: "Crafting visual layouts, conceptualizing media, or drafting storyboards",
        desc: "Visual composition, typography, interactive aesthetics, and storytelling.",
        dimensions: { creative: 5, communication: 4, people: 2, riskTaking: 2 },
      },
      {
        id: "q2_opt4",
        title: "Developing market growth strategies, financial models, or venture roadmaps",
        desc: "Analyzing competitive dynamics, commercial viability, and product growth levers.",
        dimensions: { business: 5, leadership: 4, communication: 3, analytical: 3, riskTaking: 3 },
      },
    ],
  },
  {
    id: "q3",
    category: "Decision Making",
    question: "When making an important decision with high uncertainty, what do you naturally prioritize?",
    type: "single",
    description: "The primary anchor you rely upon when the path forward is ambiguous.",
    options: [
      {
        id: "q3_opt1",
        title: "Objective metrics, statistical evidence, and quantifiable probabilities",
        desc: "Relying on numbers, quantitative rigor, and structured analytical validation.",
        dimensions: { analytical: 5, structured: 4, research: 3, technical: 1 },
      },
      {
        id: "q3_opt2",
        title: "Systematic technical feasibility, architectural soundness, and reliability",
        desc: "Verifying engineering principles, structural stability, and system constraints.",
        dimensions: { technical: 5, structured: 4, analytical: 3 },
      },
      {
        id: "q3_opt3",
        title: "Direct human impact, empathy, and positive outcomes for people",
        desc: "Prioritizing psychological well-being, user fulfillment, and social values.",
        dimensions: { people: 5, communication: 4, leadership: 2, creative: 2 },
      },
      {
        id: "q3_opt4",
        title: "Market opportunity, competitive advantage, and entrepreneurial upside",
        desc: "Capitalizing on business potential, strategic positioning, and bold innovation.",
        dimensions: { business: 5, riskTaking: 4, leadership: 3, communication: 3, analytical: 2 },
      },
    ],
  },
  {
    id: "q4",
    category: "Project Preference",
    question: "Which type of project would excite you the most to lead or contribute to?",
    type: "single",
    description: "The type of initiative that makes you eager to see the end result.",
    options: [
      {
        id: "q4_opt1",
        title: "Launching a scalable software platform, automated pipeline, or secure network",
        desc: "Delivering powerful digital products, resilient services, or intelligent software tools.",
        dimensions: { technical: 5, analytical: 3, structured: 3, riskTaking: 2 },
      },
      {
        id: "q4_opt2",
        title: "Uncovering scientific insights, discovering health breakthroughs, or analyzing complex datasets",
        desc: "Advancing knowledge in healthcare, scientific research, or predictive intelligence.",
        dimensions: { research: 5, analytical: 4, people: 2, structured: 3 },
      },
      {
        id: "q4_opt3",
        title: "Producing an iconic creative campaign, brand identity, or multimedia experience",
        desc: "Engaging wide audiences through visual artistry, compelling media, or interactive design.",
        dimensions: { creative: 5, communication: 4, riskTaking: 3, people: 2 },
      },
      {
        id: "q4_opt4",
        title: "Building an entrepreneurial venture, closing high-value deals, or driving executive strategy",
        desc: "Founding an organization, scaling commercial operations, and negotiating key milestones.",
        dimensions: { business: 5, leadership: 5, communication: 3, riskTaking: 4 },
      },
    ],
  },
  {
    id: "q5",
    category: "Domain Curiosity",
    question: "Which subjects or areas spark your genuine intellectual curiosity?",
    type: "multiple",
    maxSelect: 4,
    description: "Select up to 4 fields that you find yourself reading about or discussing effortlessly.",
    options: [
      {
        id: "q5_opt1",
        title: "Software, Artificial Intelligence & Distributed Systems",
        tag: "Technology",
        dimensions: { technical: 4, analytical: 3, structured: 2 },
      },
      {
        id: "q5_opt2",
        title: "Data Science, Mathematics & Quantitative Economics",
        tag: "Data & Math",
        dimensions: { analytical: 4, research: 3, business: 2 },
      },
      {
        id: "q5_opt3",
        title: "Visual Design, Media Production & User Experience",
        tag: "Design & Arts",
        dimensions: { creative: 4, communication: 3, people: 2 },
      },
      {
        id: "q5_opt4",
        title: "Business Leadership, Finance & Corporate Strategy",
        tag: "Business",
        dimensions: { business: 4, leadership: 3, structured: 2 },
      },
      {
        id: "q5_opt5",
        title: "Healthcare, Human Physiology & Mental Wellness",
        tag: "Healthcare",
        dimensions: { people: 4, research: 3, analytical: 2 },
      },
      {
        id: "q5_opt6",
        title: "Law, Governance, Ethics & Public Policy",
        tag: "Public Affairs",
        dimensions: { communication: 4, structured: 3, leadership: 2, research: 2 },
      },
      {
        id: "q5_opt7",
        title: "Core Engineering, Architecture & Physical Construction",
        tag: "Engineering",
        dimensions: { structured: 4, technical: 3, creative: 2, analytical: 2 },
      },
      {
        id: "q5_opt8",
        title: "Venture Creation, Entrepreneurship & Product Innovation",
        tag: "Ventures",
        dimensions: { riskTaking: 4, business: 3, leadership: 3, creative: 2 },
      },
    ],
  },
  {
    id: "q6",
    category: "Collaboration Role",
    question: "In a collaborative team, which role do you naturally gravitate toward?",
    type: "single",
    description: "How you contribute your best energy when working alongside others.",
    options: [
      {
        id: "q6_opt1",
        title: "The Technical Problem Solver: Tackling intricate mechanisms and building the core engine",
        desc: "Focusing on functionality, writing code, and resolving technical bottlenecks.",
        dimensions: { technical: 5, analytical: 3, structured: 3 },
      },
      {
        id: "q6_opt2",
        title: "The Creative Innovator: Imagining novel visual concepts, storytelling, and divergent ideas",
        desc: "Infusing creative originality, user aesthetics, and out-of-the-box perspectives.",
        dimensions: { creative: 5, riskTaking: 3, communication: 2 },
      },
      {
        id: "q6_opt3",
        title: "The Strategist & Organizer: Coordinating timelines, priorities, and business execution",
        desc: "Setting clear milestones, unblocking team members, and aligning with broad goals.",
        dimensions: { leadership: 5, business: 4, communication: 3, structured: 2 },
      },
      {
        id: "q6_opt4",
        title: "The Counselor & Communicator: Supporting people, resolving friction, and building empathy",
        desc: "Ensuring psychological safety, mentoring colleagues, and facilitating clear dialogue.",
        dimensions: { people: 5, communication: 4, leadership: 2 },
      },
    ],
  },
  {
    id: "q7",
    category: "Career Motivations",
    question: "Which achievements and rewards would make you feel most proud of your career?",
    type: "multiple",
    maxSelect: 3,
    description: "Select up to 3 core drivers that matter most to your long-term fulfillment.",
    options: [
      {
        id: "q7_opt1",
        title: "Mastering complex intellectual challenges and cutting-edge technology",
        desc: "Continuous intellectual stimulation and deep technical craftsmanship.",
        dimensions: { technical: 4, analytical: 4, research: 2 },
      },
      {
        id: "q7_opt2",
        title: "Transforming raw ideas into tangible products or captivating works of art",
        desc: "Bringing novel visual, literary, or functional creations to life.",
        dimensions: { creative: 4, riskTaking: 3, technical: 2 },
      },
      {
        id: "q7_opt3",
        title: "Scaling a business, generating high financial value, or steering company growth",
        desc: "Commercial expansion, high financial returns, and executive responsibility.",
        dimensions: { business: 4, leadership: 3, riskTaking: 3 },
      },
      {
        id: "q7_opt4",
        title: "Directly improving human health, saving lives, or empowering others through mentorship",
        desc: "Creating profound, measurable improvements in real people's lives.",
        dimensions: { people: 5, communication: 2, structured: 1 },
      },
      {
        id: "q7_opt5",
        title: "Discovering fundamental scientific truths, authoring research, or analytical breakthroughs",
        desc: "Expanding academic or scientific frontiers through rigorous inquiry.",
        dimensions: { research: 5, analytical: 3, structured: 2 },
      },
      {
        id: "q7_opt6",
        title: "Directing organizational strategy, public policy, or industry-wide initiatives",
        desc: "Exercising high-level leadership and influential institutional governance.",
        dimensions: { leadership: 4, communication: 3, business: 2 },
      },
      {
        id: "q7_opt7",
        title: "Establishing reliable, orderly, and highly stable operational processes",
        desc: "Creating structural certainty, regulatory compliance, and dependable order.",
        dimensions: { structured: 5, analytical: 2, business: 2 },
      },
    ],
  },
  {
    id: "q8",
    category: "Work Environment",
    question: "Which working rhythm and operational environment brings out your peak output?",
    type: "single",
    description: "The physical and cultural setting where you do your best work.",
    options: [
      {
        id: "q8_opt1",
        title: "High autonomy, deep individual focus, minimal meetings, and technical clarity",
        desc: "Independent problem solving with deep concentration and quantitative milestones.",
        dimensions: { technical: 4, research: 3, structured: 3 },
      },
      {
        id: "q8_opt2",
        title: "A dynamic, fast-evolving venture setting where adaptability and risk are embraced",
        desc: "Agile, experimental environment with rapid pivots and high growth potential.",
        dimensions: { riskTaking: 5, business: 4, creative: 3, leadership: 3, communication: 3 },
      },
      {
        id: "q8_opt3",
        title: "A collaborative, empathetic setting centered around direct human interaction",
        desc: "Team rooms, consulting spaces, clinical settings, or teaching environments.",
        dimensions: { people: 5, communication: 4, leadership: 2 },
      },
      {
        id: "q8_opt4",
        title: "A well-structured, methodical institution with clear standards and prestige",
        desc: "Established corporations, public institutions, or medical and legal centers.",
        dimensions: { structured: 5, analytical: 3, business: 2 },
      },
    ],
  },
  {
    id: "q9",
    category: "Ambiguity & Risk",
    question: "How comfortable are you navigating uncertain requirements, unmapped goals, and real risk?",
    type: "rating",
    min: 1,
    max: 5,
    description: "Rate your comfort level from 1 (Strong preference for structure) to 5 (Thrive in high-risk ambiguity).",
    scaleLabels: [
      { value: 1, label: "Prefer Structured Certainty", note: "Best in well-defined roles with established procedures." },
      { value: 2, label: "Moderate Structure Preferred", note: "Comfortable with minor adaptations inside clear boundaries." },
      { value: 3, label: "Balanced Flexibility", note: "Navigate moderate uncertainty when backed by solid research." },
      { value: 4, label: "Energized by Exploration", note: "Welcome calculated risks and iterative trial-and-error." },
      { value: 5, label: "Thrive in High Ambiguity", note: "Excited by bold frontiers, pioneering ventures, and uncertainty." },
    ],
    // Rating contributions to dimensions
    ratingDimensions: {
      1: { structured: 5, analytical: 3, riskTaking: 0 },
      2: { structured: 4, analytical: 2, riskTaking: 1 },
      3: { structured: 2, analytical: 3, research: 2, riskTaking: 2 },
      4: { riskTaking: 4, creative: 3, business: 2 },
      5: { riskTaking: 5, creative: 4, leadership: 3, business: 2 },
    },
  },
  {
    id: "q10",
    category: "Long-Term Legacy",
    question: "Looking ahead over the arc of your career, which legacy would feel most fulfilling?",
    type: "scenario",
    description: "The signature contribution you wish to look back on with pride.",
    options: [
      {
        id: "q10_opt1",
        title: "Having engineered mission-critical technological infrastructure or software used by millions",
        desc: "Being recognized as a master builder of robust, high-impact digital systems.",
        dimensions: { technical: 5, analytical: 4, structured: 3 },
      },
      {
        id: "q10_opt2",
        title: "Having made pivotal scientific discoveries, authored influential research, or advanced healthcare",
        desc: "Contributing foundational knowledge, clinical healing, or deep analytical solutions.",
        dimensions: { research: 5, analytical: 4, structured: 3 },
      },
      {
        id: "q10_opt3",
        title: "Having created iconic design works, artistic productions, or unforgettable brand experiences",
        desc: "Delighting millions through aesthetic brilliance, cultural storytelling, and visual creativity.",
        dimensions: { creative: 5, communication: 4, riskTaking: 3 },
      },
      {
        id: "q10_opt4",
        title: "Having founded and scaled successful enterprises or led major commercial transformations",
        desc: "Building sustainable organizations, creating jobs, and steering economic progress.",
        dimensions: { business: 5, leadership: 5, communication: 4, riskTaking: 4 },
      },
      {
        id: "q10_opt5",
        title: "Having saved lives, treated patients, educated students, or mentored people to their potential",
        desc: "Creating lasting personal transformations and uplifting human welfare directly.",
        dimensions: { people: 5, communication: 4, leadership: 2 },
      },
      {
        id: "q10_opt6",
        title: "Having upheld justice, shaped ethical public policy, or reformed vital societal systems",
        desc: "Ensuring fairness, regulatory integrity, and societal progress through structured leadership.",
        dimensions: { structured: 4, leadership: 4, communication: 4, research: 2 },
      },
    ],
  },
];

// 4. Comprehensive Career Profiles Mapped Exactly to Growvia Roadmap IDs in MongoDB
// Normalized 0–100 profile vector for each eligible career roadmap
export const CAREER_PROFILES = {
  // ── Technology ──────────────────────────────────────────────
  "engineer": {
    family: "technology",
    title: "Software Engineer",
    category: "Technology",
    icon: "Code",
    description: "Design, develop, and maintain robust web platforms, distributed systems, and software applications.",
    dimensions: {
      technical: 92,
      analytical: 86,
      creative: 50,
      business: 36,
      communication: 48,
      leadership: 40,
      research: 62,
      people: 28,
      structured: 78,
      riskTaking: 42,
    },
    keyStrengths: ["Algorithmic problem solving", "System architecture & design", "Clean code craftsmanship"],
    skillsToDevelop: ["Distributed systems", "CI/CD infrastructure", "High-level architectural planning"],
  },
  "ai-ml-engineer": {
    family: "data",
    title: "AI / ML Engineer",
    category: "Technology",
    icon: "Brain",
    description: "Develop neural network architectures, machine learning models, and intelligent predictive algorithms.",
    dimensions: {
      technical: 88,
      analytical: 94,
      creative: 52,
      business: 44,
      communication: 46,
      leadership: 35,
      research: 88,
      people: 25,
      structured: 75,
      riskTaking: 50,
    },
    keyStrengths: ["Mathematical modeling", "Deep neural networks", "Scientific curiosity"],
    skillsToDevelop: ["Production MLOps pipelines", "Model inference optimization", "Data cleaning & feature engineering"],
  },
  "data-scientist": {
    family: "data",
    title: "Data Scientist",
    category: "Technology",
    icon: "BarChart2",
    description: "Transform multi-dimensional datasets into predictive models, business intelligence, and scientific insights.",
    dimensions: {
      technical: 78,
      analytical: 95,
      creative: 48,
      business: 62,
      communication: 58,
      leadership: 38,
      research: 90,
      people: 30,
      structured: 76,
      riskTaking: 38,
    },
    keyStrengths: ["Statistical inference & hypothesis testing", "Data storytelling & visualization", "Analytical rigor"],
    skillsToDevelop: ["Advanced Big Data querying", "Business stakeholder translation", "Automated forecasting pipelines"],
  },
  "cybersecurity": {
    family: "technology",
    title: "Cybersecurity Analyst",
    category: "Technology",
    icon: "Shield",
    description: "Defend enterprise systems, protocols, and confidential data against malicious intrusions and vulnerabilities.",
    dimensions: {
      technical: 88,
      analytical: 88,
      creative: 40,
      business: 46,
      communication: 50,
      leadership: 42,
      research: 76,
      people: 28,
      structured: 92,
      riskTaking: 36,
    },
    keyStrengths: ["Threat intelligence & reconnaissance", "Network protocol security", "Meticulous defense protocols"],
    skillsToDevelop: ["Automated penetration testing", "Incident response orchestration", "Zero-trust architecture"],
  },
  "cloud-architect": {
    family: "technology",
    title: "Cloud Architect",
    category: "Technology",
    icon: "Cloud",
    description: "Design multi-region cloud infrastructures, scalable containerized clusters, and high-availability systems.",
    dimensions: {
      technical: 94,
      analytical: 82,
      creative: 42,
      business: 58,
      communication: 60,
      leadership: 55,
      research: 60,
      people: 32,
      structured: 84,
      riskTaking: 45,
    },
    keyStrengths: ["Scalable distributed systems", "Infrastructure-as-Code automation", "Disaster recovery planning"],
    skillsToDevelop: ["FinOps cloud cost governance", "Kubernetes cluster tuning", "Multi-cloud migration strategy"],
  },
  "game-developer": {
    family: "technology",
    title: "Game Developer",
    category: "Technology & Gaming",
    icon: "Gamepad2",
    description: "Build interactive virtual worlds, graphics engines, game physics, and gameplay mechanics.",
    dimensions: {
      technical: 88,
      analytical: 78,
      creative: 84,
      business: 35,
      communication: 45,
      leadership: 38,
      research: 52,
      people: 32,
      structured: 65,
      riskTaking: 60,
    },
    keyStrengths: ["Game physics & 3D math", "Interactive gameplay loops", "Creative world building"],
    skillsToDevelop: ["Shader programming", "Memory & framerate optimization", "Multiplayer network sync"],
  },
  "blockchain-developer": {
    family: "technology",
    title: "Blockchain Developer",
    category: "Technology",
    icon: "Boxes",
    description: "Develop decentralized protocols, cryptographically verified smart contracts, and Web3 architectures.",
    dimensions: {
      technical: 92,
      analytical: 88,
      creative: 45,
      business: 56,
      communication: 44,
      leadership: 40,
      research: 72,
      people: 24,
      structured: 86,
      riskTaking: 65,
    },
    keyStrengths: ["Cryptographic fundamentals", "Smart contract security", "Decentralized consensus design"],
    skillsToDevelop: ["Smart contract formal verification", "Gas optimization techniques", "Zero-knowledge proofs"],
  },

  // ── Design & Creative ───────────────────────────────────────
  "designer": {
    family: "design",
    title: "UI/UX Designer",
    category: "Design",
    icon: "Palette",
    description: "Craft seamless, human-centered digital experiences, wireframes, visual hierarchies, and interactive prototypes.",
    dimensions: {
      technical: 44,
      analytical: 62,
      creative: 95,
      business: 52,
      communication: 78,
      leadership: 45,
      research: 68,
      people: 82,
      structured: 60,
      riskTaking: 52,
    },
    keyStrengths: ["User empathy & behavior observation", "Visual systems & UI craftsmanship", "Interactive prototyping"],
    skillsToDevelop: ["Quantitative usability testing", "Design system engineering", "Accessibility compliance (WCAG)"],
  },
  "graphic-designer": {
    family: "design",
    title: "Graphic Designer",
    category: "Creative & Design",
    icon: "Sparkles",
    description: "Create compelling visual identities, brand typography, marketing materials, and digital graphics.",
    dimensions: {
      technical: 38,
      analytical: 48,
      creative: 96,
      business: 46,
      communication: 72,
      leadership: 35,
      research: 45,
      people: 60,
      structured: 52,
      riskTaking: 58,
    },
    keyStrengths: ["Brand visual storytelling", "Typographic sensitivity", "Creative visual flair"],
    skillsToDevelop: ["Motion design basics", "Print production nuances", "Brand strategy alignment"],
  },
  "interior-designer": {
    family: "design",
    title: "Interior Designer",
    category: "Design & Built Environment",
    icon: "Home",
    description: "Transform architectural spaces into functional, visually striking, and comfortable environments.",
    dimensions: {
      technical: 50,
      analytical: 58,
      creative: 92,
      business: 56,
      communication: 74,
      leadership: 50,
      research: 48,
      people: 75,
      structured: 72,
      riskTaking: 50,
    },
    keyStrengths: ["Spatial organization & ergonomics", "Material & lighting aesthetics", "Client consultation"],
    skillsToDevelop: ["3D rendering software proficiency", "Building code compliance", "Vendor budget negotiation"],
  },
  "fashion-designer": {
    family: "design",
    title: "Fashion Designer",
    category: "Creative & Design",
    icon: "Scissors",
    description: "Design innovative apparel, seasonal collections, textile aesthetics, and runway concepts.",
    dimensions: {
      technical: 40,
      analytical: 45,
      creative: 98,
      business: 60,
      communication: 68,
      leadership: 52,
      research: 55,
      people: 58,
      structured: 48,
      riskTaking: 75,
    },
    keyStrengths: ["Trend forecasting & visual innovation", "Garment silhouette construction", "Aesthetic conviction"],
    skillsToDevelop: ["Sustainable textile sourcing", "Apparel supply chain dynamics", "Digital CAD fashion rendering"],
  },
  "architect": {
    family: "design",
    title: "Architect",
    category: "Design & Construction",
    icon: "Building2",
    description: "Design physical structures, integrating aesthetic grandeur with engineering stability and environmental safety.",
    dimensions: {
      technical: 72,
      analytical: 80,
      creative: 90,
      business: 58,
      communication: 70,
      leadership: 65,
      research: 68,
      people: 55,
      structured: 86,
      riskTaking: 50,
    },
    keyStrengths: ["Spatial vision & 3D modeling", "Engineering-design harmony", "Structural integrity assessment"],
    skillsToDevelop: ["BIM (Building Information Modeling)", "Sustainable building green standards", "Urban zoning regulation"],
  },

  // ── Business & Management ───────────────────────────────────
  "product-manager": {
    family: "business",
    title: "Product Manager",
    category: "Technology",
    icon: "Compass",
    description: "Guide products from inception to scale, bridging engineering, user research, and executive strategy.",
    dimensions: {
      technical: 56,
      analytical: 78,
      creative: 72,
      business: 92,
      communication: 90,
      leadership: 90,
      research: 66,
      people: 78,
      structured: 68,
      riskTaking: 68,
    },
    keyStrengths: ["Product roadmap prioritization", "Cross-functional team leadership", "Data-informed decision making"],
    skillsToDevelop: ["Technical API architecture fundamentals", "Customer discovery interviewing", "Growth metric modeling"],
  },
  "startup-founder": {
    family: "business",
    title: "Startup Founder",
    category: "Business",
    icon: "Rocket",
    description: "Found and scale innovative enterprises from the ground up, solving high-value customer needs under uncertainty.",
    dimensions: {
      technical: 54,
      analytical: 76,
      creative: 80,
      business: 96,
      communication: 88,
      leadership: 96,
      research: 65,
      people: 76,
      structured: 50,
      riskTaking: 98,
    },
    keyStrengths: ["Relentless visionary grit", "High risk tolerance & resourcefulness", "Strategic storytelling & fundraising"],
    skillsToDevelop: ["Capital allocation & cap-table management", "Hiring & team culture building", "Product-market fit validation"],
  },
  "mba-manager": {
    family: "business",
    title: "MBA / Business Manager",
    category: "Business & Management",
    icon: "Briefcase",
    description: "Direct corporate operations, strategic initiatives, cross-functional organizational units, and market expansion.",
    dimensions: {
      technical: 42,
      analytical: 80,
      creative: 55,
      business: 92,
      communication: 88,
      leadership: 88,
      research: 58,
      people: 74,
      structured: 82,
      riskTaking: 60,
    },
    keyStrengths: ["Executive resource allocation", "Organizational change management", "Commercial strategy synthesis"],
    skillsToDevelop: ["Data-driven operational dashboards", "Cross-cultural negotiation", "P&L responsibility management"],
  },
  "human-resources": {
    family: "business",
    title: "Human Resources (HR)",
    category: "Business & Management",
    icon: "Users",
    description: "Champion organizational culture, talent acquisition, people development, and employee relations.",
    dimensions: {
      technical: 30,
      analytical: 58,
      creative: 52,
      business: 72,
      communication: 92,
      leadership: 74,
      research: 50,
      people: 96,
      structured: 80,
      riskTaking: 36,
    },
    keyStrengths: ["Interpersonal empathy & trust building", "Talent assessment & development", "Conflict mediation"],
    skillsToDevelop: ["People analytics & retention modeling", "Labor law compliance", "Compensation benchmarking"],
  },
  "supply-chain": {
    family: "operations",
    title: "Supply Chain / Logistics Manager",
    category: "Operations & Logistics",
    icon: "Truck",
    description: "Orchestrate global procurement, freight networks, inventory optimization, and distribution reliability.",
    dimensions: {
      technical: 52,
      analytical: 84,
      creative: 40,
      business: 82,
      communication: 72,
      leadership: 70,
      research: 54,
      people: 56,
      structured: 92,
      riskTaking: 42,
    },
    keyStrengths: ["Logistical route optimization", "Vendor contract management", "High-reliability process design"],
    skillsToDevelop: ["ERP software deep configuration", "Predictive demand forecasting", "Resilient risk mitigation"],
  },

  // ── Marketing & Media ───────────────────────────────────────
  "digital-marketer": {
    family: "marketing",
    title: "Digital Marketer",
    category: "Marketing",
    icon: "Megaphone",
    description: "Drive digital audience acquisition, paid growth campaigns, performance marketing, and conversion optimization.",
    dimensions: {
      technical: 48,
      analytical: 78,
      creative: 82,
      business: 86,
      communication: 86,
      leadership: 60,
      research: 58,
      people: 68,
      structured: 62,
      riskTaking: 65,
    },
    keyStrengths: ["Campaign ROI optimization", "Multi-channel funnel analysis", "Audience persona targeting"],
    skillsToDevelop: ["Automated attribution modeling", "A/B multivariate statistical testing", "Content syndication"],
  },
  "marketing-manager": {
    family: "marketing",
    title: "Marketing Manager",
    category: "Business & Management",
    icon: "TrendingUp",
    description: "Lead comprehensive brand strategy, promotional budgets, product positioning, and creative campaign teams.",
    dimensions: {
      technical: 40,
      analytical: 74,
      creative: 80,
      business: 88,
      communication: 90,
      leadership: 82,
      research: 60,
      people: 74,
      structured: 70,
      riskTaking: 64,
    },
    keyStrengths: ["Brand strategy formulation", "Omnichannel marketing leadership", "Market research synthesis"],
    skillsToDevelop: ["Brand equity measurement", "High-budget media planning", "Global agency management"],
  },
  "content-creator": {
    family: "media",
    title: "Content Creator",
    category: "Media",
    icon: "Film",
    description: "Produce captivating digital video, narrative storytelling, podcasting, and audience engagement across platforms.",
    dimensions: {
      technical: 46,
      analytical: 48,
      creative: 96,
      business: 68,
      communication: 94,
      leadership: 62,
      research: 52,
      people: 76,
      structured: 44,
      riskTaking: 82,
    },
    keyStrengths: ["Audience connection & charisma", "Visual & audio narrative design", "Agile content publishing"],
    skillsToDevelop: ["Community monetization channels", "Professional video color grading", "Intellectual property licensing"],
  },
  "journalist": {
    family: "media",
    title: "Journalist / Media",
    category: "Media & Communication",
    icon: "Newspaper",
    description: "Investigate breaking events, interview key figures, uncover critical truths, and report public stories.",
    dimensions: {
      technical: 34,
      analytical: 72,
      creative: 75,
      business: 45,
      communication: 96,
      leadership: 55,
      research: 92,
      people: 78,
      structured: 68,
      riskTaking: 68,
    },
    keyStrengths: ["Incisive investigative interviewing", "Fact verification & ethics", "Persuasive editorial writing"],
    skillsToDevelop: ["Data journalism & visualization", "Digital media libel & media law", "Field audio/video recording"],
  },
  "public-relations": {
    family: "media",
    title: "Public Relations (PR)",
    category: "Media & Communication",
    icon: "Radio",
    description: "Shape organizational public perception, manage media relations, coordinate press tours, and resolve crises.",
    dimensions: {
      technical: 28,
      analytical: 60,
      creative: 74,
      business: 76,
      communication: 96,
      leadership: 72,
      research: 62,
      people: 88,
      structured: 70,
      riskTaking: 52,
    },
    keyStrengths: ["Crisis communication & messaging", "Media stakeholder network", "Narrative reputation defense"],
    skillsToDevelop: ["Sentiment analysis software", "Press release SEO distribution", "Executive media training"],
  },
  "film-director": {
    family: "media",
    title: "Film Director / Filmmaker",
    category: "Creative & Media",
    icon: "Clapperboard",
    description: "Direct cinematic productions, guide actor performances, manage cinematic pacing, and translate script to screen.",
    dimensions: {
      technical: 55,
      analytical: 58,
      creative: 98,
      business: 62,
      communication: 92,
      leadership: 90,
      research: 68,
      people: 80,
      structured: 58,
      riskTaking: 84,
    },
    keyStrengths: ["Artistic vision & composition", "Actor performance direction", "Immersive audio-visual storytelling"],
    skillsToDevelop: ["Production budget finance", "Cinematography optics technicalities", "Post-production sound mixing"],
  },
  "photographer": {
    family: "media",
    title: "Photographer / Videographer",
    category: "Creative & Media",
    icon: "Camera",
    description: "Capture striking imagery, frame documentary stories, master lighting techniques, and deliver commercial visuals.",
    dimensions: {
      technical: 60,
      analytical: 50,
      creative: 94,
      business: 54,
      communication: 70,
      leadership: 44,
      research: 48,
      people: 68,
      structured: 60,
      riskTaking: 58,
    },
    keyStrengths: ["Lighting & optical framing", "Visual aesthetic instinct", "Subject rapport & direction"],
    skillsToDevelop: ["Advanced color grading", "Commercial commercial studio lighting", "Client licensing contracts"],
  },

  // ── Finance ─────────────────────────────────────────────────
  "chartered-accountant": {
    family: "finance",
    title: "Chartered Accountant",
    category: "Finance",
    icon: "Calculator",
    description: "Audit corporate balance sheets, structure statutory tax strategies, and ensure fiscal compliance.",
    dimensions: {
      technical: 44,
      analytical: 92,
      creative: 30,
      business: 88,
      communication: 65,
      leadership: 55,
      research: 70,
      people: 42,
      structured: 98,
      riskTaking: 22,
    },
    keyStrengths: ["Statutory accounting compliance", "Tax optimization planning", "Rigorous financial accuracy"],
    skillsToDevelop: ["Forensic auditing tools", "International IFRS standards", "Corporate advisory structuring"],
  },
  "financial-analyst": {
    family: "finance",
    title: "Financial Analyst",
    category: "Finance",
    icon: "LineChart",
    description: "Evaluate corporate equity valuations, economic trends, financial statements, and investment feasibility.",
    dimensions: {
      technical: 50,
      analytical: 94,
      creative: 34,
      business: 88,
      communication: 68,
      leadership: 48,
      research: 76,
      people: 38,
      structured: 90,
      riskTaking: 42,
    },
    keyStrengths: ["Discounted cash flow (DCF) modeling", "Financial statement deconstruction", "Quantitative trend analysis"],
    skillsToDevelop: ["Python/R for quantitative finance", "Bloomberg terminal expertise", "Portfolio risk optimization"],
  },
  "investment-banker": {
    family: "finance",
    title: "Investment Banker",
    category: "Finance",
    icon: "Landmark",
    description: "Advise on mergers and acquisitions (M&A), structure initial public offerings (IPOs), and raise capital.",
    dimensions: {
      technical: 46,
      analytical: 92,
      creative: 40,
      business: 96,
      communication: 86,
      leadership: 80,
      research: 72,
      people: 60,
      structured: 88,
      riskTaking: 72,
    },
    keyStrengths: ["Complex corporate deal valuation", "High-stakes presentation polish", "Financial structuring"],
    skillsToDevelop: ["Leveraged buyout (LBO) modeling", "M&A regulatory compliance", "Syndicated debt structuring"],
  },
  "actuary": {
    family: "finance",
    title: "Actuary",
    category: "Finance",
    icon: "Percent",
    description: "Model long-term probabilities, evaluate insurance risk tables, and design pension and underwriting systems.",
    dimensions: {
      technical: 62,
      analytical: 98,
      creative: 30,
      business: 78,
      communication: 52,
      leadership: 38,
      research: 82,
      people: 26,
      structured: 96,
      riskTaking: 20,
    },
    keyStrengths: ["Stochastic probability modeling", "Actuarial science precision", "Long-term liability analysis"],
    skillsToDevelop: ["Machine learning in mortality forecasting", "Catastrophic risk modeling", "Solvency II frameworks"],
  },

  // ── Healthcare & Medicine ───────────────────────────────────
  "doctor": {
    family: "healthcare",
    title: "Medical Doctor",
    category: "Healthcare",
    icon: "HeartPulse",
    description: "Diagnose, treat, and care for patients in clinical, surgical, or hospital settings with profound commitment.",
    dimensions: {
      technical: 54,
      analytical: 88,
      creative: 38,
      business: 42,
      communication: 78,
      leadership: 70,
      research: 80,
      people: 96,
      structured: 92,
      riskTaking: 38,
    },
    keyStrengths: ["Clinical diagnosis precision", "Patient empathy & active listening", "High-pressure decision making"],
    skillsToDevelop: ["Sub-specialty diagnostic surgical mastery", "Evidence-based clinical research", "Healthcare systems management"],
  },
  "dentist": {
    family: "healthcare",
    title: "Dentist (BDS)",
    category: "Healthcare",
    icon: "SmilePlus",
    description: "Diagnose and treat oral health conditions, perform dental surgeries, and restore smiles.",
    dimensions: {
      technical: 65,
      analytical: 76,
      creative: 68,
      business: 65,
      communication: 76,
      leadership: 60,
      research: 60,
      people: 86,
      structured: 88,
      riskTaking: 32,
    },
    keyStrengths: ["Fine motor dexterity & precision", "Esthetic oral reconstruction", "Patient anxiety management"],
    skillsToDevelop: ["Advanced implantology", "Cosmetic veneer design", "Private clinic business operations"],
  },
  "physiotherapist": {
    family: "healthcare",
    title: "Physiotherapist",
    category: "Healthcare",
    icon: "Activity",
    description: "Rehabilitate patients recovering from injury or illness through physical therapy, movement, and exercise.",
    dimensions: {
      technical: 45,
      analytical: 72,
      creative: 55,
      business: 52,
      communication: 82,
      leadership: 55,
      research: 62,
      people: 94,
      structured: 80,
      riskTaking: 30,
    },
    keyStrengths: ["Musculoskeletal biomechanics", "Patient encouragement & rehabilitation", "Hands-on physical diagnosis"],
    skillsToDevelop: ["Sports injury kinetics", "Neurological rehab protocols", "Ergonomic workplace consulting"],
  },
  "pharmacist": {
    family: "healthcare",
    title: "Pharmacist",
    category: "Healthcare",
    icon: "Pill",
    description: "Dispense medications, ensure patient drug safety, advise on pharmacological interactions, and formulate compounds.",
    dimensions: {
      technical: 52,
      analytical: 82,
      creative: 32,
      business: 60,
      communication: 74,
      leadership: 48,
      research: 70,
      people: 80,
      structured: 96,
      riskTaking: 18,
    },
    keyStrengths: ["Pharmacological chemistry", "Drug interaction verification", "High attention to medical safety"],
    skillsToDevelop: ["Clinical pharmacokinetics", "Biomedical compounding", "Pharmacy inventory governance"],
  },
  "psychologist": {
    family: "healthcare",
    title: "Psychologist",
    category: "Mental Health",
    icon: "Smile",
    description: "Support emotional well-being, conduct psychotherapy, explore behavioral cognitive patterns, and empower clients.",
    dimensions: {
      technical: 30,
      analytical: 76,
      creative: 62,
      business: 46,
      communication: 92,
      leadership: 56,
      research: 82,
      people: 98,
      structured: 72,
      riskTaking: 32,
    },
    keyStrengths: ["Empathetic non-judgmental listening", "Cognitive behavioral therapy (CBT)", "Human behavioral insight"],
    skillsToDevelop: ["Psychometric test administration", "Specialized trauma care methodologies", "Clinical research publishing"],
  },

  // ── Law & Public Service ────────────────────────────────────
  "lawyer": {
    family: "legal",
    title: "Corporate Lawyer",
    category: "Legal",
    icon: "Scale",
    description: "Counsel corporations on governance, regulatory compliance, contract drafting, mergers, and legal advocacy.",
    dimensions: {
      technical: 34,
      analytical: 92,
      creative: 46,
      business: 86,
      communication: 95,
      leadership: 78,
      research: 88,
      people: 62,
      structured: 94,
      riskTaking: 45,
    },
    keyStrengths: ["Contractual precision & drafting", "Adversarial negotiation & persuasion", "Statutory interpretation"],
    skillsToDevelop: ["International commercial arbitration", "Intellectual property technology patents", "Antitrust regulation"],
  },
  "civil-services": {
    family: "legal",
    title: "Civil Services (IAS / IPS)",
    category: "Government & Public Service",
    icon: "ShieldAlert",
    description: "Administer public districts, enforce law and order, implement government welfare, and lead civil governance.",
    dimensions: {
      technical: 40,
      analytical: 84,
      creative: 48,
      business: 72,
      communication: 90,
      leadership: 96,
      research: 76,
      people: 88,
      structured: 92,
      riskTaking: 52,
    },
    keyStrengths: ["Public policy execution", "Crisis management under pressure", "Administrative authority & leadership"],
    skillsToDevelop: ["Public finance budgeting", "E-governance digital transformation", "Disaster response logistics"],
  },
  "army-officer": {
    family: "legal",
    title: "Army Officer",
    category: "Government & Defence",
    icon: "Award",
    description: "Lead armed forces personnel, execute tactical operations, maintain national defense, and embody disciplined command.",
    dimensions: {
      technical: 58,
      analytical: 74,
      creative: 40,
      business: 45,
      communication: 78,
      leadership: 98,
      research: 52,
      people: 75,
      structured: 98,
      riskTaking: 78,
    },
    keyStrengths: ["Supreme operational discipline", "Tactical battlefield strategy", "High-stress situational leadership"],
    skillsToDevelop: ["Modern defense technology & drone systems", "Strategic geopolitical intelligence", "Advanced logistics"],
  },

  // ── Core Engineering ────────────────────────────────────────
  "civil-engineer": {
    family: "engineering",
    title: "Civil Engineer",
    category: "Engineering",
    icon: "HardHat",
    description: "Plan, construct, and oversee municipal bridges, roadways, dams, and modern urban infrastructure projects.",
    dimensions: {
      technical: 78,
      analytical: 84,
      creative: 55,
      business: 60,
      communication: 64,
      leadership: 68,
      research: 60,
      people: 48,
      structured: 92,
      riskTaking: 38,
    },
    keyStrengths: ["Structural physics calculations", "On-site construction management", "Quality material testing"],
    skillsToDevelop: ["AutoCAD & Civil 3D software", "Geotechnical soil testing", "Smart city sustainable design"],
  },
  "mechanical-engineer": {
    family: "engineering",
    title: "Mechanical Engineer",
    category: "Engineering",
    icon: "Cog",
    description: "Design mechanical machinery, thermal engines, robotic automation, and manufacturing tooling.",
    dimensions: {
      technical: 86,
      analytical: 88,
      creative: 62,
      business: 52,
      communication: 58,
      leadership: 55,
      research: 68,
      people: 36,
      structured: 88,
      riskTaking: 42,
    },
    keyStrengths: ["Thermodynamics & fluid mechanics", "CAD manufacturing modeling", "Robotic kinematics"],
    skillsToDevelop: ["Finite Element Analysis (FEA)", "Additive manufacturing (3D printing)", "Mechatronics integration"],
  },

  // ── Education & Social Sciences ─────────────────────────────
  "teacher": {
    family: "education",
    title: "Teacher / Educator",
    category: "Education",
    icon: "GraduationCap",
    description: "Inspire, teach, and mentor students through structured curriculum design, pedagogical clarity, and patience.",
    dimensions: {
      technical: 32,
      analytical: 64,
      creative: 72,
      business: 36,
      communication: 95,
      leadership: 78,
      research: 72,
      people: 96,
      structured: 84,
      riskTaking: 30,
    },
    keyStrengths: ["Pedagogical simplification", "Student inspiration & empathy", "Patience and classroom leadership"],
    skillsToDevelop: ["Interactive digital learning tools", "Personalized educational assessment", "Special educational needs adaptations"],
  },
  "ed-tech": {
    family: "education",
    title: "Ed-Tech / Online Educator",
    category: "Education & Technology",
    icon: "MonitorPlay",
    description: "Create interactive digital courses, scalable learning platforms, video tutorials, and modern educational cohorts.",
    dimensions: {
      technical: 62,
      analytical: 70,
      creative: 82,
      business: 75,
      communication: 94,
      leadership: 72,
      research: 68,
      people: 88,
      structured: 70,
      riskTaking: 62,
    },
    keyStrengths: ["Engaging video lesson delivery", "Curriculum structure for remote learners", "Community cohort facilitation"],
    skillsToDevelop: ["LMS architecture & analytics", "Gamified learning mechanics", "High-retention student workflows"],
  },
  "social-worker": {
    family: "social",
    title: "Social Worker / NGO",
    category: "Social Sciences",
    icon: "HeartHandshake",
    description: "Empower marginalized communities, provide social casework, lead humanitarian relief, and advocate for human rights.",
    dimensions: {
      technical: 22,
      analytical: 58,
      creative: 55,
      business: 50,
      communication: 90,
      leadership: 76,
      research: 65,
      people: 99,
      structured: 70,
      riskTaking: 48,
    },
    keyStrengths: ["Unconditional human empathy", "Grassroots community mobilization", "Trauma and crisis support"],
    skillsToDevelop: ["Grant proposal writing", "Non-profit fiscal governance", "Sociological field research"],
  },

  // ── Science & Research ──────────────────────────────────────
  "biotechnologist": {
    family: "science",
    title: "Biotechnologist",
    category: "Science & Research",
    icon: "Dna",
    description: "Engineer biological organisms, genetic therapies, vaccine formulations, and advanced agricultural improvements.",
    dimensions: {
      technical: 74,
      analytical: 92,
      creative: 55,
      business: 52,
      communication: 60,
      leadership: 44,
      research: 96,
      people: 42,
      structured: 88,
      riskTaking: 45,
    },
    keyStrengths: ["Molecular genetics & assay testing", "Cell culture laboratory rigor", "Scientific hypothesis validation"],
    skillsToDevelop: ["CRISPR gene editing techniques", "Bioinformatics Python packages", "Biopharmaceutical clinical trials"],
  },
  "environmental-scientist": {
    family: "science",
    title: "Environmental Scientist",
    category: "Science & Environment",
    icon: "Leaf",
    description: "Analyze ecological balance, monitor pollution levels, assess climate impact, and champion environmental sustainability.",
    dimensions: {
      technical: 62,
      analytical: 88,
      creative: 50,
      business: 54,
      communication: 74,
      leadership: 55,
      research: 94,
      people: 60,
      structured: 82,
      riskTaking: 40,
    },
    keyStrengths: ["Environmental impact assessment", "Ecological field sampling", "Climate data analysis"],
    skillsToDevelop: ["GIS spatial mapping software", "Carbon footprint auditing", "Environmental compliance policy"],
  },

  // ── Health & Wellness ───────────────────────────────────────
  "nutritionist": {
    family: "wellness",
    title: "Nutritionist / Dietitian",
    category: "Health & Wellness",
    icon: "Apple",
    description: "Create personalized dietary protocols, optimize metabolic health, manage clinical nutritional therapies, and coach lifestyle wellness.",
    dimensions: {
      technical: 40,
      analytical: 74,
      creative: 58,
      business: 58,
      communication: 86,
      leadership: 55,
      research: 76,
      people: 92,
      structured: 82,
      riskTaking: 30,
    },
    keyStrengths: ["Nutritional biochemistry", "Personalized diet coaching", "Patient empathy and motivation"],
    skillsToDevelop: ["Sports nutrition periodization", "Gut microbiome analysis", "Clinical dietetics documentation"],
  },
  "fitness-trainer": {
    family: "wellness",
    title: "Fitness Trainer / Sports Coach",
    category: "Health & Wellness",
    icon: "Dumbbell",
    description: "Coach athletic performance, design strength conditioning regimens, correct movement patterns, and build physical resilience.",
    dimensions: {
      technical: 42,
      analytical: 62,
      creative: 60,
      business: 64,
      communication: 88,
      leadership: 85,
      research: 52,
      people: 90,
      structured: 78,
      riskTaking: 45,
    },
    keyStrengths: ["Biomechanical form coaching", "Energetic team motivation", "Progressive overload programming"],
    skillsToDevelop: ["Athletic recovery science", "Kinesiology injury prevention", "Personal training business marketing"],
  },

  // ── Hospitality & Aviation ──────────────────────────────────
  "pilot": {
    family: "hospitality",
    title: "Commercial Pilot",
    category: "Aviation & Transport",
    icon: "Plane",
    description: "Navigate passenger and cargo aircraft safely across global airspace, managing flight instruments, weather, and cockpit crew.",
    dimensions: {
      technical: 86,
      analytical: 84,
      creative: 30,
      business: 40,
      communication: 82,
      leadership: 88,
      research: 52,
      people: 55,
      structured: 99,
      riskTaking: 45,
    },
    keyStrengths: ["High-speed spatial decision making", "Avionics instrument mastery", "Uncompromising safety checklists"],
    skillsToDevelop: ["Advanced instrument flight rating (IFR)", "Multi-crew cockpit resource management", "Adverse weather navigation"],
  },
  "hotel-management": {
    family: "hospitality",
    title: "Hotel Management / Hospitality",
    category: "Business & Hospitality",
    icon: "Hotel",
    description: "Oversee luxury guest experiences, hotel operations, culinary services, revenue management, and hospitality teams.",
    dimensions: {
      technical: 32,
      analytical: 65,
      creative: 68,
      business: 85,
      communication: 92,
      leadership: 82,
      research: 42,
      people: 94,
      structured: 84,
      riskTaking: 46,
    },
    keyStrengths: ["Luxury customer service excellence", "Front-of-house operations", "Team morale and leadership"],
    skillsToDevelop: ["Hotel revenue & yield management", "Hospitality property management systems (PMS)", "Food & beverage cost control"],
  },
  "event-manager": {
    family: "hospitality",
    title: "Event Manager",
    category: "Business & Hospitality",
    icon: "CalendarCheck",
    description: "Orchestrate large-scale conferences, concerts, corporate summits, and weddings with meticulous production planning.",
    dimensions: {
      technical: 40,
      analytical: 68,
      creative: 85,
      business: 82,
      communication: 94,
      leadership: 86,
      research: 50,
      people: 88,
      structured: 86,
      riskTaking: 62,
    },
    keyStrengths: ["Live event coordination under pressure", "Creative experiential design", "Vendor budget negotiation"],
    skillsToDevelop: ["Audio-visual stage production logistics", "Crowd safety risk assessment", "Corporate sponsor acquisition"],
  },
};

/**
 * Helper to dynamically generate a calibrated dimension profile for any newly added
 * or custom course in MongoDB that is not in the predefined matrix above.
 * Ensures that if a new roadmap is published by an admin, it becomes instantly eligible!
 */
export const inferCourseProfile = (course = {}) => {
  const category = (course.category || "").toLowerCase();
  const title = (course.title || "").toLowerCase();
  const skills = (course.skills || []).map((s) => s.toLowerCase());

  let family = "technology";
  const dims = {
    technical: 50,
    analytical: 50,
    creative: 50,
    business: 50,
    communication: 50,
    leadership: 50,
    research: 50,
    people: 50,
    structured: 50,
    riskTaking: 50,
  };

  if (category.includes("tech") || category.includes("code") || title.includes("developer")) {
    family = "technology";
    dims.technical = 85;
    dims.analytical = 80;
    dims.structured = 75;
  } else if (category.includes("data") || title.includes("analyst") || title.includes("data")) {
    family = "data";
    dims.analytical = 90;
    dims.research = 82;
    dims.technical = 75;
  } else if (category.includes("design") || category.includes("creative") || title.includes("designer")) {
    family = "design";
    dims.creative = 92;
    dims.communication = 75;
    dims.people = 70;
  } else if (category.includes("business") || category.includes("manage") || title.includes("manager")) {
    family = "business";
    dims.business = 90;
    dims.leadership = 85;
    dims.communication = 80;
  } else if (category.includes("health") || category.includes("med") || title.includes("doctor")) {
    family = "healthcare";
    dims.people = 92;
    dims.structured = 85;
    dims.analytical = 78;
  } else if (category.includes("finance") || category.includes("account")) {
    family = "finance";
    dims.analytical = 90;
    dims.structured = 90;
    dims.business = 85;
  } else if (category.includes("market")) {
    family = "marketing";
    dims.communication = 88;
    dims.business = 84;
    dims.creative = 80;
  } else if (category.includes("media")) {
    family = "media";
    dims.creative = 88;
    dims.communication = 92;
    dims.riskTaking = 70;
  }

  // Adjust for skills
  if (skills.some((s) => s.includes("code") || s.includes("programming") || s.includes("python"))) {
    dims.technical = Math.min(95, dims.technical + 15);
  }
  if (skills.some((s) => s.includes("lead") || s.includes("management"))) {
    dims.leadership = Math.min(95, dims.leadership + 15);
  }
  if (skills.some((s) => s.includes("design") || s.includes("art"))) {
    dims.creative = Math.min(95, dims.creative + 15);
  }

  return {
    family,
    title: course.title,
    category: course.category,
    icon: course.icon || "Briefcase",
    description: course.description || `Master the career roadmap for ${course.title}.`,
    dimensions: dims,
    keyStrengths: course.skills?.slice(0, 3) || ["Professional competence", "Problem solving"],
    skillsToDevelop: ["Foundational domain concepts", "Practical project implementation"],
  };
};
