/**
 * Centralized Career Assessment Configuration for Growvia
 * Standardized across 10 core career dimensions and mapped directly
 * to available database roadmaps with family-aware diversity classification.
 */

// 1. The 10 Core Career Dimensions (0–100 normalized score)
export const DIMENSION_KEYS = [
  "technical",
  "analytical",
  "creative",
  "business",
  "communication",
  "leadership",
  "research",
  "people",
  "structured",
  "riskTaking",
];

export const DIMENSION_LABELS = {
  technical: "Technical & Systems",
  analytical: "Analytical & Logic",
  creative: "Creative & Design",
  business: "Business & Strategy",
  communication: "Communication & Expression",
  leadership: "Leadership & Initiative",
  research: "Research & Investigation",
  people: "People & Empathy",
  structured: "Structure & Process",
  riskTaking: "Innovation & Risk Tolerance",
};

export const DIMENSION_DESCRIPTIONS = {
  technical: "Aptitude for coding, software architecture, infrastructure, and engineering mechanisms.",
  analytical: "Strength in quantitative logic, data analysis, pattern recognition, and mathematical deduction.",
  creative: "Intuition for aesthetic design, visual storytelling, artistic expression, and divergent thinking.",
  business: "Acumen for market dynamics, commercial growth, financial modeling, and strategic ROI.",
  communication: "Fluency in articulating concepts, stakeholder persuasion, writing, and presentation.",
  leadership: "Ability to inspire teams, steer roadmap vision, take ownership, and drive execution.",
  research: "Dedication to methodical exploration, literature synthesis, hypothesis testing, and deep inquiry.",
  people: "Empathy, active listening, psychological insight, mentorship, and service to others.",
  structured: "Affinity for systematic workflows, meticulous compliance, discipline, and order.",
  riskTaking: "Comfort with ambiguity, experimentation, unmapped territories, and entrepreneurial risk.",
};

// Relative dimension importance weights for similarity scoring
export const DIMENSION_WEIGHTS = {
  technical: 1.15,
  analytical: 1.20,
  creative: 1.05,
  business: 1.10,
  communication: 1.05,
  leadership: 1.00,
  research: 1.00,
  people: 0.95,
  structured: 0.90,
  riskTaking: 0.85,
};

// 2. Primary Career Families for Diversity-Aware Filtering
export const CAREER_FAMILIES = {
  technology: "Technology & Software",
  data: "Data & AI",
  design: "Design & Creative",
  business: "Business & Management",
  marketing: "Marketing & Growth",
  finance: "Finance & Accounting",
  healthcare: "Healthcare & Medicine",
  legal: "Law & Governance",
  media: "Media & Communication",
  engineering: "Core Engineering",
  education: "Education & Training",
  social: "Social Sciences & Welfare",
  science: "Science & Environment",
  operations: "Operations & Logistics",
  wellness: "Health & Wellness",
  hospitality: "Hospitality & Aviation",
};

// 2.1 Standardized 8 Core Career Categories for Weighted Score Vectors
export const CAREER_CATEGORIES = {
  medicine: {
    id: "medicine",
    label: "Healthcare & Medicine",
    family: "healthcare",
    icon: "HeartPulse",
    defaultRoadmapId: "doctor",
    roadmaps: ["doctor", "physiotherapist", "pharmacist", "nutritionist", "psychologist"],
    description: "Diagnose, treat, heal, and improve physical and mental health.",
  },
  law: {
    id: "law",
    label: "Law & Governance",
    family: "legal",
    icon: "Scale",
    defaultRoadmapId: "lawyer",
    roadmaps: ["lawyer", "civil-services"],
    description: "Advise on legal rights, uphold justice, and shape public policy.",
  },
  technology: {
    id: "technology",
    label: "Software & Technology",
    family: "technology",
    icon: "Code",
    defaultRoadmapId: "engineer",
    roadmaps: ["engineer", "data-scientist", "cybersecurity", "ai-specialist", "devops"],
    description: "Build robust software, digital tools, AI platforms, and cloud systems.",
  },
  design: {
    id: "design",
    label: "Design & Creative Arts",
    family: "design",
    icon: "Palette",
    defaultRoadmapId: "designer",
    roadmaps: ["designer", "interior-designer", "fashion-designer", "animator", "architect"],
    description: "Create visual experiences, user interfaces, physical spaces, and media.",
  },
  business: {
    id: "business",
    label: "Business & Management",
    family: "business",
    icon: "Briefcase",
    defaultRoadmapId: "product-manager",
    roadmaps: ["product-manager", "digital-marketer", "hr-specialist", "supply-chain"],
    description: "Lead organizations, manage teams, launch products, and grow ventures.",
  },
  finance: {
    id: "finance",
    label: "Finance & Accounting",
    family: "finance",
    icon: "TrendingUp",
    defaultRoadmapId: "chartered-accountant",
    roadmaps: ["chartered-accountant", "financial-analyst", "investment-banker"],
    description: "Manage capital, analyze financial markets, optimize tax, and invest.",
  },
  engineering: {
    id: "engineering",
    label: "Core Engineering",
    family: "engineering",
    icon: "Wrench",
    defaultRoadmapId: "mechanical-engineer",
    roadmaps: ["mechanical-engineer", "civil-engineer", "electrical-engineer", "robotics-engineer"],
    description: "Design physical machines, durable buildings, robotics, and engines.",
  },
  education: {
    id: "education",
    label: "Education & Care",
    family: "education",
    icon: "GraduationCap",
    defaultRoadmapId: "teacher",
    roadmaps: ["teacher", "academic-researcher", "counselor"],
    description: "Teach concepts, mentor learners, and foster human development.",
  },
};

export const CATEGORY_KEYS = Object.keys(CAREER_CATEGORIES);

// 3. 10 High-Precision Career Assessment Questions (Simple, Short Scenarios with Weighted Score Vectors)
// 4 Academic Questions (40% Weight, Multiplier: 0.8) + 6 Interest Questions (60% Weight, Multiplier: 1.2)
export const QUIZ_QUESTIONS = [
  {
    id: "q1",
    typeCategory: "academic",
    weight: 0.8,
    category: "School Interests",
    question: "Which school subject did you enjoy studying the most?",
    type: "single",
    description: "Pick the subject that felt easiest and most engaging to you.",
    options: [
      {
        id: "q1_opt1",
        title: "Biology and human anatomy",
        scores: { medicine: 3, education: 1 },
      },
      {
        id: "q1_opt2",
        title: "History, civics, and political debate",
        scores: { law: 3, education: 1 },
      },
      {
        id: "q1_opt3",
        title: "Computer science and coding logic",
        scores: { technology: 3, engineering: 2 },
      },
      {
        id: "q1_opt4",
        title: "Art, drafting, and graphic design",
        scores: { design: 3 },
      },
      {
        id: "q1_opt5",
        title: "Math, business studies, and economics",
        scores: { finance: 3, business: 2 },
      },
      {
        id: "q1_opt6",
        title: "Physics, machines, and mechanics",
        scores: { engineering: 3, technology: 1 },
      },
    ],
  },
  {
    id: "q2",
    typeCategory: "academic",
    weight: 0.8,
    category: "Learning Style",
    question: "How do you prefer solving a difficult homework assignment?",
    type: "single",
    description: "Your default problem-solving instinct when studying.",
    options: [
      {
        id: "q2_opt1",
        title: "Diagnosing real medical or biological examples",
        scores: { medicine: 3, education: 1 },
      },
      {
        id: "q2_opt2",
        title: "Finding legal or ethical arguments in texts",
        scores: { law: 3, business: 1 },
      },
      {
        id: "q2_opt3",
        title: "Writing code or step-by-step logic formulas",
        scores: { technology: 3, engineering: 2 },
      },
      {
        id: "q2_opt4",
        title: "Drawing diagrams, sketches, and visual mind-maps",
        scores: { design: 3, education: 1 },
      },
      {
        id: "q2_opt5",
        title: "Calculating numbers and spreadsheets for business",
        scores: { finance: 3, business: 2 },
      },
      {
        id: "q2_opt6",
        title: "Building physical models or testing equipment",
        scores: { engineering: 3, technology: 1 },
      },
    ],
  },
  {
    id: "q3",
    typeCategory: "academic",
    weight: 0.8,
    category: "Class Projects",
    question: "What kind of school project was most fun to present?",
    type: "single",
    description: "The topic where you enjoyed sharing your work with others.",
    options: [
      {
        id: "q3_opt1",
        title: "A health survey or biology experiment",
        scores: { medicine: 3, education: 2 },
      },
      {
        id: "q3_opt2",
        title: "A mock court trial or debate",
        scores: { law: 3, business: 1 },
      },
      {
        id: "q3_opt3",
        title: "A working website or computer app",
        scores: { technology: 3, design: 1 },
      },
      {
        id: "q3_opt4",
        title: "An art portfolio or fashion showcase",
        scores: { design: 3 },
      },
      {
        id: "q3_opt5",
        title: "A business plan selling a product",
        scores: { business: 3, finance: 2 },
      },
      {
        id: "q3_opt6",
        title: "A working robot or machine model",
        scores: { engineering: 3, technology: 1 },
      },
    ],
  },
  {
    id: "q4",
    typeCategory: "academic",
    weight: 0.8,
    category: "Reading & Curiosity",
    question: "When reading a textbook, what catches your interest first?",
    type: "single",
    description: "The sections or figures that immediately draw your eye.",
    options: [
      {
        id: "q4_opt1",
        title: "Medical breakthroughs and health tips",
        scores: { medicine: 3, education: 1 },
      },
      {
        id: "q4_opt2",
        title: "Court trials and human rights cases",
        scores: { law: 3, business: 1 },
      },
      {
        id: "q4_opt3",
        title: "Code snippets and algorithm charts",
        scores: { technology: 3, engineering: 1 },
      },
      {
        id: "q4_opt4",
        title: "Visual photos, typography, and page layout",
        scores: { design: 3 },
      },
      {
        id: "q4_opt5",
        title: "Company revenue tables and market trends",
        scores: { finance: 3, business: 3 },
      },
      {
        id: "q4_opt6",
        title: "Diagrams of engines, circuits, and bridges",
        scores: { engineering: 3, technology: 1 },
      },
    ],
  },
  {
    id: "q5",
    typeCategory: "interest",
    weight: 1.2,
    category: "Daily Preference",
    question: "Would you rather fix a broken gadget or write a story?",
    type: "single",
    description: "Choose the hands-on activity that sounds most appealing.",
    options: [
      {
        id: "q5_opt1",
        title: "Treat an injured pet or someone hurting",
        scores: { medicine: 3, education: 2 },
      },
      {
        id: "q5_opt2",
        title: "Settle a dispute and defend fair rules",
        scores: { law: 3, business: 1 },
      },
      {
        id: "q5_opt3",
        title: "Fix computer software or write new code",
        scores: { technology: 3, engineering: 1 },
      },
      {
        id: "q5_opt4",
        title: "Sketch a logo, room layout, or outfit",
        scores: { design: 3 },
      },
      {
        id: "q5_opt5",
        title: "Sell items online to make a profit",
        scores: { business: 3, finance: 2 },
      },
      {
        id: "q5_opt6",
        title: "Repair a broken motor, bicycle, or gadget",
        scores: { engineering: 3, technology: 1 },
      },
    ],
  },
  {
    id: "q6",
    typeCategory: "interest",
    weight: 1.2,
    category: "Weekend Activity",
    question: "If you had a free weekend, what would you do?",
    type: "single",
    description: "How you naturally love spending your leisure hours.",
    options: [
      {
        id: "q6_opt1",
        title: "Volunteer at a community health camp",
        scores: { medicine: 3, education: 2 },
      },
      {
        id: "q6_opt2",
        title: "Watch court trials and legal documentaries",
        scores: { law: 3, education: 1 },
      },
      {
        id: "q6_opt3",
        title: "Build a video game or website",
        scores: { technology: 3, design: 1 },
      },
      {
        id: "q6_opt4",
        title: "Paint, take photos, or edit creative videos",
        scores: { design: 3 },
      },
      {
        id: "q6_opt5",
        title: "Research stock prices or startup ideas",
        scores: { finance: 3, business: 3 },
      },
      {
        id: "q6_opt6",
        title: "Build a DIY drone or wooden furniture",
        scores: { engineering: 3, technology: 1 },
      },
    ],
  },
  {
    id: "q7",
    typeCategory: "interest",
    weight: 1.2,
    category: "Dream Workplace",
    question: "Which workplace would you enjoy visiting the most?",
    type: "single",
    description: "The work environment that makes you feel excited.",
    options: [
      {
        id: "q7_opt1",
        title: "A modern hospital or wellness clinic",
        scores: { medicine: 3, education: 1 },
      },
      {
        id: "q7_opt2",
        title: "A high-court room or law office",
        scores: { law: 3, business: 1 },
      },
      {
        id: "q7_opt3",
        title: "A software company building smart apps",
        scores: { technology: 3, engineering: 1 },
      },
      {
        id: "q7_opt4",
        title: "A design studio or film set",
        scores: { design: 3 },
      },
      {
        id: "q7_opt5",
        title: "A stock exchange or corporate office",
        scores: { business: 3, finance: 2 },
      },
      {
        id: "q7_opt6",
        title: "A robotics lab or construction site",
        scores: { engineering: 3, technology: 1 },
      },
    ],
  },
  {
    id: "q8",
    typeCategory: "interest",
    weight: 1.2,
    category: "Problem Solving",
    question: "What kind of problem do you love solving?",
    type: "single",
    description: "The challenges that spark your curiosity.",
    options: [
      {
        id: "q8_opt1",
        title: "Finding why someone feels unwell or sick",
        scores: { medicine: 3, education: 1 },
      },
      {
        id: "q8_opt2",
        title: "Settling an argument between two opposing sides",
        scores: { law: 3, business: 1 },
      },
      {
        id: "q8_opt3",
        title: "Finding and fixing bugs in a program",
        scores: { technology: 3, engineering: 1 },
      },
      {
        id: "q8_opt4",
        title: "Redesigning an ugly poster or messy room",
        scores: { design: 3 },
      },
      {
        id: "q8_opt5",
        title: "Finding ways to invest and grow money",
        scores: { finance: 3, business: 2 },
      },
      {
        id: "q8_opt6",
        title: "Fixing a broken machine or mechanical toy",
        scores: { engineering: 3, technology: 1 },
      },
    ],
  },
  {
    id: "q9",
    typeCategory: "interest",
    weight: 1.2,
    category: "Team Contribution",
    question: "In a group project with friends, what role fits you?",
    type: "single",
    description: "How you naturally help your team succeed.",
    options: [
      {
        id: "q9_opt1",
        title: "Caring for everyone and helping them succeed",
        scores: { medicine: 2, education: 3 },
      },
      {
        id: "q9_opt2",
        title: "Defending our points and arguing for fairness",
        scores: { law: 3, business: 1 },
      },
      {
        id: "q9_opt3",
        title: "Managing the computer code and tech tools",
        scores: { technology: 3, engineering: 1 },
      },
      {
        id: "q9_opt4",
        title: "Designing the slides, graphics, and visual look",
        scores: { design: 3 },
      },
      {
        id: "q9_opt5",
        title: "Leading the team and planning the budget",
        scores: { business: 3, finance: 2 },
      },
      {
        id: "q9_opt6",
        title: "Assembling physical models and testing equipment",
        scores: { engineering: 3, technology: 1 },
      },
    ],
  },
  {
    id: "q10",
    typeCategory: "interest",
    weight: 1.2,
    category: "Proud Achievement",
    question: "What accomplishment would make you feel most proud?",
    type: "single",
    description: "The long-term impact that means the most to you.",
    options: [
      {
        id: "q10_opt1",
        title: "Helping patients heal and recover their health",
        scores: { medicine: 3, education: 1 },
      },
      {
        id: "q10_opt2",
        title: "Defending an innocent person in court",
        scores: { law: 3, business: 1 },
      },
      {
        id: "q10_opt3",
        title: "Building an app downloaded by millions",
        scores: { technology: 3, design: 1 },
      },
      {
        id: "q10_opt4",
        title: "Creating an iconic artwork or building",
        scores: { design: 3, engineering: 1 },
      },
      {
        id: "q10_opt5",
        title: "Growing a company into a thriving business",
        scores: { business: 3, finance: 2 },
      },
      {
        id: "q10_opt6",
        title: "Designing a safe bridge or useful robot",
        scores: { engineering: 3, technology: 1 },
      },
    ],
  },
];

// 4. Comprehensive Career Profiles Mapped Exactly to Growvia Roadmap IDs in MongoDB
// Normalized 0–100 profile vector for each eligible career roadmap
export const CAREER_PROFILES = {
  // ── Technology ──────────────────────────────────────────────
  "engineer": {
    family: "technology",
    title: "Software Engineer",
    category: "Technology",
    icon: "Code",
    description: "Design, develop, and maintain robust web platforms, distributed systems, and software applications.",
    dimensions: {
      technical: 92,
      analytical: 86,
      creative: 50,
      business: 36,
      communication: 48,
      leadership: 40,
      research: 62,
      people: 28,
      structured: 78,
      riskTaking: 42,
    },
    keyStrengths: ["Algorithmic problem solving", "System architecture & design", "Clean code craftsmanship"],
    skillsToDevelop: ["Distributed systems", "CI/CD infrastructure", "High-level architectural planning"],
  },
  "ai-ml-engineer": {
    family: "data",
    title: "AI / ML Engineer",
    category: "Technology",
    icon: "Brain",
    description: "Develop neural network architectures, machine learning models, and intelligent predictive algorithms.",
    dimensions: {
      technical: 88,
      analytical: 94,
      creative: 52,
      business: 44,
      communication: 46,
      leadership: 35,
      research: 88,
      people: 25,
      structured: 75,
      riskTaking: 50,
    },
    keyStrengths: ["Mathematical modeling", "Deep neural networks", "Scientific curiosity"],
    skillsToDevelop: ["Production MLOps pipelines", "Model inference optimization", "Data cleaning & feature engineering"],
  },
  "data-scientist": {
    family: "data",
    title: "Data Scientist",
    category: "Technology",
    icon: "BarChart2",
    description: "Transform multi-dimensional datasets into predictive models, business intelligence, and scientific insights.",
    dimensions: {
      technical: 78,
      analytical: 95,
      creative: 48,
      business: 62,
      communication: 58,
      leadership: 38,
      research: 90,
      people: 30,
      structured: 76,
      riskTaking: 38,
    },
    keyStrengths: ["Statistical inference & hypothesis testing", "Data storytelling & visualization", "Analytical rigor"],
    skillsToDevelop: ["Advanced Big Data querying", "Business stakeholder translation", "Automated forecasting pipelines"],
  },
  "cybersecurity": {
    family: "technology",
    title: "Cybersecurity Analyst",
    category: "Technology",
    icon: "Shield",
    description: "Defend enterprise systems, protocols, and confidential data against malicious intrusions and vulnerabilities.",
    dimensions: {
      technical: 88,
      analytical: 88,
      creative: 40,
      business: 46,
      communication: 50,
      leadership: 42,
      research: 76,
      people: 28,
      structured: 92,
      riskTaking: 36,
    },
    keyStrengths: ["Threat intelligence & reconnaissance", "Network protocol security", "Meticulous defense protocols"],
    skillsToDevelop: ["Automated penetration testing", "Incident response orchestration", "Zero-trust architecture"],
  },
  "cloud-architect": {
    family: "technology",
    title: "Cloud Architect",
    category: "Technology",
    icon: "Cloud",
    description: "Design multi-region cloud infrastructures, scalable containerized clusters, and high-availability systems.",
    dimensions: {
      technical: 94,
      analytical: 82,
      creative: 42,
      business: 58,
      communication: 60,
      leadership: 55,
      research: 60,
      people: 32,
      structured: 84,
      riskTaking: 45,
    },
    keyStrengths: ["Scalable distributed systems", "Infrastructure-as-Code automation", "Disaster recovery planning"],
    skillsToDevelop: ["FinOps cloud cost governance", "Kubernetes cluster tuning", "Multi-cloud migration strategy"],
  },
  "game-developer": {
    family: "technology",
    title: "Game Developer",
    category: "Technology & Gaming",
    icon: "Gamepad2",
    description: "Build interactive virtual worlds, graphics engines, game physics, and gameplay mechanics.",
    dimensions: {
      technical: 88,
      analytical: 78,
      creative: 84,
      business: 35,
      communication: 45,
      leadership: 38,
      research: 52,
      people: 32,
      structured: 65,
      riskTaking: 60,
    },
    keyStrengths: ["Game physics & 3D math", "Interactive gameplay loops", "Creative world building"],
    skillsToDevelop: ["Shader programming", "Memory & framerate optimization", "Multiplayer network sync"],
  },
  "blockchain-developer": {
    family: "technology",
    title: "Blockchain Developer",
    category: "Technology",
    icon: "Boxes",
    description: "Develop decentralized protocols, cryptographically verified smart contracts, and Web3 architectures.",
    dimensions: {
      technical: 92,
      analytical: 88,
      creative: 45,
      business: 56,
      communication: 44,
      leadership: 40,
      research: 72,
      people: 24,
      structured: 86,
      riskTaking: 65,
    },
    keyStrengths: ["Cryptographic fundamentals", "Smart contract security", "Decentralized consensus design"],
    skillsToDevelop: ["Smart contract formal verification", "Gas optimization techniques", "Zero-knowledge proofs"],
  },

  // ── Design & Creative ───────────────────────────────────────
  "designer": {
    family: "design",
    title: "UI/UX Designer",
    category: "Design",
    icon: "Palette",
    description: "Craft seamless, human-centered digital experiences, wireframes, visual hierarchies, and interactive prototypes.",
    dimensions: {
      technical: 44,
      analytical: 62,
      creative: 95,
      business: 52,
      communication: 78,
      leadership: 45,
      research: 68,
      people: 82,
      structured: 60,
      riskTaking: 52,
    },
    keyStrengths: ["User empathy & behavior observation", "Visual systems & UI craftsmanship", "Interactive prototyping"],
    skillsToDevelop: ["Quantitative usability testing", "Design system engineering", "Accessibility compliance (WCAG)"],
  },
  "graphic-designer": {
    family: "design",
    title: "Graphic Designer",
    category: "Creative & Design",
    icon: "Sparkles",
    description: "Create compelling visual identities, brand typography, marketing materials, and digital graphics.",
    dimensions: {
      technical: 38,
      analytical: 48,
      creative: 96,
      business: 46,
      communication: 72,
      leadership: 35,
      research: 45,
      people: 60,
      structured: 52,
      riskTaking: 58,
    },
    keyStrengths: ["Brand visual storytelling", "Typographic sensitivity", "Creative visual flair"],
    skillsToDevelop: ["Motion design basics", "Print production nuances", "Brand strategy alignment"],
  },
  "interior-designer": {
    family: "design",
    title: "Interior Designer",
    category: "Design & Built Environment",
    icon: "Home",
    description: "Transform architectural spaces into functional, visually striking, and comfortable environments.",
    dimensions: {
      technical: 50,
      analytical: 58,
      creative: 92,
      business: 56,
      communication: 74,
      leadership: 50,
      research: 48,
      people: 75,
      structured: 72,
      riskTaking: 50,
    },
    keyStrengths: ["Spatial organization & ergonomics", "Material & lighting aesthetics", "Client consultation"],
    skillsToDevelop: ["3D rendering software proficiency", "Building code compliance", "Vendor budget negotiation"],
  },
  "fashion-designer": {
    family: "design",
    title: "Fashion Designer",
    category: "Creative & Design",
    icon: "Scissors",
    description: "Design innovative apparel, seasonal collections, textile aesthetics, and runway concepts.",
    dimensions: {
      technical: 40,
      analytical: 45,
      creative: 98,
      business: 60,
      communication: 68,
      leadership: 52,
      research: 55,
      people: 58,
      structured: 48,
      riskTaking: 75,
    },
    keyStrengths: ["Trend forecasting & visual innovation", "Garment silhouette construction", "Aesthetic conviction"],
    skillsToDevelop: ["Sustainable textile sourcing", "Apparel supply chain dynamics", "Digital CAD fashion rendering"],
  },
  "architect": {
    family: "design",
    title: "Architect",
    category: "Design & Construction",
    icon: "Building2",
    description: "Design physical structures, integrating aesthetic grandeur with engineering stability and environmental safety.",
    dimensions: {
      technical: 72,
      analytical: 80,
      creative: 90,
      business: 58,
      communication: 70,
      leadership: 65,
      research: 68,
      people: 55,
      structured: 86,
      riskTaking: 50,
    },
    keyStrengths: ["Spatial vision & 3D modeling", "Engineering-design harmony", "Structural integrity assessment"],
    skillsToDevelop: ["BIM (Building Information Modeling)", "Sustainable building green standards", "Urban zoning regulation"],
  },

  // ── Business & Management ───────────────────────────────────
  "product-manager": {
    family: "business",
    title: "Product Manager",
    category: "Technology",
    icon: "Compass",
    description: "Guide products from inception to scale, bridging engineering, user research, and executive strategy.",
    dimensions: {
      technical: 56,
      analytical: 78,
      creative: 72,
      business: 92,
      communication: 90,
      leadership: 90,
      research: 66,
      people: 78,
      structured: 68,
      riskTaking: 68,
    },
    keyStrengths: ["Product roadmap prioritization", "Cross-functional team leadership", "Data-informed decision making"],
    skillsToDevelop: ["Technical API architecture fundamentals", "Customer discovery interviewing", "Growth metric modeling"],
  },
  "startup-founder": {
    family: "business",
    title: "Startup Founder",
    category: "Business",
    icon: "Rocket",
    description: "Found and scale innovative enterprises from the ground up, solving high-value customer needs under uncertainty.",
    dimensions: {
      technical: 54,
      analytical: 76,
      creative: 80,
      business: 96,
      communication: 88,
      leadership: 96,
      research: 65,
      people: 76,
      structured: 50,
      riskTaking: 98,
    },
    keyStrengths: ["Relentless visionary grit", "High risk tolerance & resourcefulness", "Strategic storytelling & fundraising"],
    skillsToDevelop: ["Capital allocation & cap-table management", "Hiring & team culture building", "Product-market fit validation"],
  },
  "mba-manager": {
    family: "business",
    title: "MBA / Business Manager",
    category: "Business & Management",
    icon: "Briefcase",
    description: "Direct corporate operations, strategic initiatives, cross-functional organizational units, and market expansion.",
    dimensions: {
      technical: 42,
      analytical: 80,
      creative: 55,
      business: 92,
      communication: 88,
      leadership: 88,
      research: 58,
      people: 74,
      structured: 82,
      riskTaking: 60,
    },
    keyStrengths: ["Executive resource allocation", "Organizational change management", "Commercial strategy synthesis"],
    skillsToDevelop: ["Data-driven operational dashboards", "Cross-cultural negotiation", "P&L responsibility management"],
  },
  "human-resources": {
    family: "business",
    title: "Human Resources (HR)",
    category: "Business & Management",
    icon: "Users",
    description: "Champion organizational culture, talent acquisition, people development, and employee relations.",
    dimensions: {
      technical: 30,
      analytical: 58,
      creative: 52,
      business: 72,
      communication: 92,
      leadership: 74,
      research: 50,
      people: 96,
      structured: 80,
      riskTaking: 36,
    },
    keyStrengths: ["Interpersonal empathy & trust building", "Talent assessment & development", "Conflict mediation"],
    skillsToDevelop: ["People analytics & retention modeling", "Labor law compliance", "Compensation benchmarking"],
  },
  "supply-chain": {
    family: "operations",
    title: "Supply Chain / Logistics Manager",
    category: "Operations & Logistics",
    icon: "Truck",
    description: "Orchestrate global procurement, freight networks, inventory optimization, and distribution reliability.",
    dimensions: {
      technical: 52,
      analytical: 84,
      creative: 40,
      business: 82,
      communication: 72,
      leadership: 70,
      research: 54,
      people: 56,
      structured: 92,
      riskTaking: 42,
    },
    keyStrengths: ["Logistical route optimization", "Vendor contract management", "High-reliability process design"],
    skillsToDevelop: ["ERP software deep configuration", "Predictive demand forecasting", "Resilient risk mitigation"],
  },

  // ── Marketing & Media ───────────────────────────────────────
  "digital-marketer": {
    family: "marketing",
    title: "Digital Marketer",
    category: "Marketing",
    icon: "Megaphone",
    description: "Drive digital audience acquisition, paid growth campaigns, performance marketing, and conversion optimization.",
    dimensions: {
      technical: 48,
      analytical: 78,
      creative: 82,
      business: 86,
      communication: 86,
      leadership: 60,
      research: 58,
      people: 68,
      structured: 62,
      riskTaking: 65,
    },
    keyStrengths: ["Campaign ROI optimization", "Multi-channel funnel analysis", "Audience persona targeting"],
    skillsToDevelop: ["Automated attribution modeling", "A/B multivariate statistical testing", "Content syndication"],
  },
  "marketing-manager": {
    family: "marketing",
    title: "Marketing Manager",
    category: "Business & Management",
    icon: "TrendingUp",
    description: "Lead comprehensive brand strategy, promotional budgets, product positioning, and creative campaign teams.",
    dimensions: {
      technical: 40,
      analytical: 74,
      creative: 80,
      business: 88,
      communication: 90,
      leadership: 82,
      research: 60,
      people: 74,
      structured: 70,
      riskTaking: 64,
    },
    keyStrengths: ["Brand strategy formulation", "Omnichannel marketing leadership", "Market research synthesis"],
    skillsToDevelop: ["Brand equity measurement", "High-budget media planning", "Global agency management"],
  },
  "content-creator": {
    family: "media",
    title: "Content Creator",
    category: "Media",
    icon: "Film",
    description: "Produce captivating digital video, narrative storytelling, podcasting, and audience engagement across platforms.",
    dimensions: {
      technical: 46,
      analytical: 48,
      creative: 96,
      business: 68,
      communication: 94,
      leadership: 62,
      research: 52,
      people: 76,
      structured: 44,
      riskTaking: 82,
    },
    keyStrengths: ["Audience connection & charisma", "Visual & audio narrative design", "Agile content publishing"],
    skillsToDevelop: ["Community monetization channels", "Professional video color grading", "Intellectual property licensing"],
  },
  "journalist": {
    family: "media",
    title: "Journalist / Media",
    category: "Media & Communication",
    icon: "Newspaper",
    description: "Investigate breaking events, interview key figures, uncover critical truths, and report public stories.",
    dimensions: {
      technical: 34,
      analytical: 72,
      creative: 75,
      business: 45,
      communication: 96,
      leadership: 55,
      research: 92,
      people: 78,
      structured: 68,
      riskTaking: 68,
    },
    keyStrengths: ["Incisive investigative interviewing", "Fact verification & ethics", "Persuasive editorial writing"],
    skillsToDevelop: ["Data journalism & visualization", "Digital media libel & media law", "Field audio/video recording"],
  },
  "public-relations": {
    family: "media",
    title: "Public Relations (PR)",
    category: "Media & Communication",
    icon: "Radio",
    description: "Shape organizational public perception, manage media relations, coordinate press tours, and resolve crises.",
    dimensions: {
      technical: 28,
      analytical: 60,
      creative: 74,
      business: 76,
      communication: 96,
      leadership: 72,
      research: 62,
      people: 88,
      structured: 70,
      riskTaking: 52,
    },
    keyStrengths: ["Crisis communication & messaging", "Media stakeholder network", "Narrative reputation defense"],
    skillsToDevelop: ["Sentiment analysis software", "Press release SEO distribution", "Executive media training"],
  },
  "film-director": {
    family: "media",
    title: "Film Director / Filmmaker",
    category: "Creative & Media",
    icon: "Clapperboard",
    description: "Direct cinematic productions, guide actor performances, manage cinematic pacing, and translate script to screen.",
    dimensions: {
      technical: 55,
      analytical: 58,
      creative: 98,
      business: 62,
      communication: 92,
      leadership: 90,
      research: 68,
      people: 80,
      structured: 58,
      riskTaking: 84,
    },
    keyStrengths: ["Artistic vision & composition", "Actor performance direction", "Immersive audio-visual storytelling"],
    skillsToDevelop: ["Production budget finance", "Cinematography optics technicalities", "Post-production sound mixing"],
  },
  "photographer": {
    family: "media",
    title: "Photographer / Videographer",
    category: "Creative & Media",
    icon: "Camera",
    description: "Capture striking imagery, frame documentary stories, master lighting techniques, and deliver commercial visuals.",
    dimensions: {
      technical: 60,
      analytical: 50,
      creative: 94,
      business: 54,
      communication: 70,
      leadership: 44,
      research: 48,
      people: 68,
      structured: 60,
      riskTaking: 58,
    },
    keyStrengths: ["Lighting & optical framing", "Visual aesthetic instinct", "Subject rapport & direction"],
    skillsToDevelop: ["Advanced color grading", "Commercial commercial studio lighting", "Client licensing contracts"],
  },

  // ── Finance ─────────────────────────────────────────────────
  "chartered-accountant": {
    family: "finance",
    title: "Chartered Accountant",
    category: "Finance",
    icon: "Calculator",
    description: "Audit corporate balance sheets, structure statutory tax strategies, and ensure fiscal compliance.",
    dimensions: {
      technical: 44,
      analytical: 92,
      creative: 30,
      business: 88,
      communication: 65,
      leadership: 55,
      research: 70,
      people: 42,
      structured: 98,
      riskTaking: 22,
    },
    keyStrengths: ["Statutory accounting compliance", "Tax optimization planning", "Rigorous financial accuracy"],
    skillsToDevelop: ["Forensic auditing tools", "International IFRS standards", "Corporate advisory structuring"],
  },
  "financial-analyst": {
    family: "finance",
    title: "Financial Analyst",
    category: "Finance",
    icon: "LineChart",
    description: "Evaluate corporate equity valuations, economic trends, financial statements, and investment feasibility.",
    dimensions: {
      technical: 50,
      analytical: 94,
      creative: 34,
      business: 88,
      communication: 68,
      leadership: 48,
      research: 76,
      people: 38,
      structured: 90,
      riskTaking: 42,
    },
    keyStrengths: ["Discounted cash flow (DCF) modeling", "Financial statement deconstruction", "Quantitative trend analysis"],
    skillsToDevelop: ["Python/R for quantitative finance", "Bloomberg terminal expertise", "Portfolio risk optimization"],
  },
  "investment-banker": {
    family: "finance",
    title: "Investment Banker",
    category: "Finance",
    icon: "Landmark",
    description: "Advise on mergers and acquisitions (M&A), structure initial public offerings (IPOs), and raise capital.",
    dimensions: {
      technical: 46,
      analytical: 92,
      creative: 40,
      business: 96,
      communication: 86,
      leadership: 80,
      research: 72,
      people: 60,
      structured: 88,
      riskTaking: 72,
    },
    keyStrengths: ["Complex corporate deal valuation", "High-stakes presentation polish", "Financial structuring"],
    skillsToDevelop: ["Leveraged buyout (LBO) modeling", "M&A regulatory compliance", "Syndicated debt structuring"],
  },
  "actuary": {
    family: "finance",
    title: "Actuary",
    category: "Finance",
    icon: "Percent",
    description: "Model long-term probabilities, evaluate insurance risk tables, and design pension and underwriting systems.",
    dimensions: {
      technical: 62,
      analytical: 98,
      creative: 30,
      business: 78,
      communication: 52,
      leadership: 38,
      research: 82,
      people: 26,
      structured: 96,
      riskTaking: 20,
    },
    keyStrengths: ["Stochastic probability modeling", "Actuarial science precision", "Long-term liability analysis"],
    skillsToDevelop: ["Machine learning in mortality forecasting", "Catastrophic risk modeling", "Solvency II frameworks"],
  },

  // ── Healthcare & Medicine ───────────────────────────────────
  "doctor": {
    family: "healthcare",
    title: "Medical Doctor",
    category: "Healthcare",
    icon: "HeartPulse",
    description: "Diagnose, treat, and care for patients in clinical, surgical, or hospital settings with profound commitment.",
    dimensions: {
      technical: 54,
      analytical: 88,
      creative: 38,
      business: 42,
      communication: 78,
      leadership: 70,
      research: 80,
      people: 96,
      structured: 92,
      riskTaking: 38,
    },
    keyStrengths: ["Clinical diagnosis precision", "Patient empathy & active listening", "High-pressure decision making"],
    skillsToDevelop: ["Sub-specialty diagnostic surgical mastery", "Evidence-based clinical research", "Healthcare systems management"],
  },
  "dentist": {
    family: "healthcare",
    title: "Dentist (BDS)",
    category: "Healthcare",
    icon: "SmilePlus",
    description: "Diagnose and treat oral health conditions, perform dental surgeries, and restore smiles.",
    dimensions: {
      technical: 65,
      analytical: 76,
      creative: 68,
      business: 65,
      communication: 76,
      leadership: 60,
      research: 60,
      people: 86,
      structured: 88,
      riskTaking: 32,
    },
    keyStrengths: ["Fine motor dexterity & precision", "Esthetic oral reconstruction", "Patient anxiety management"],
    skillsToDevelop: ["Advanced implantology", "Cosmetic veneer design", "Private clinic business operations"],
  },
  "physiotherapist": {
    family: "healthcare",
    title: "Physiotherapist",
    category: "Healthcare",
    icon: "Activity",
    description: "Rehabilitate patients recovering from injury or illness through physical therapy, movement, and exercise.",
    dimensions: {
      technical: 45,
      analytical: 72,
      creative: 55,
      business: 52,
      communication: 82,
      leadership: 55,
      research: 62,
      people: 94,
      structured: 80,
      riskTaking: 30,
    },
    keyStrengths: ["Musculoskeletal biomechanics", "Patient encouragement & rehabilitation", "Hands-on physical diagnosis"],
    skillsToDevelop: ["Sports injury kinetics", "Neurological rehab protocols", "Ergonomic workplace consulting"],
  },
  "pharmacist": {
    family: "healthcare",
    title: "Pharmacist",
    category: "Healthcare",
    icon: "Pill",
    description: "Dispense medications, ensure patient drug safety, advise on pharmacological interactions, and formulate compounds.",
    dimensions: {
      technical: 52,
      analytical: 82,
      creative: 32,
      business: 60,
      communication: 74,
      leadership: 48,
      research: 70,
      people: 80,
      structured: 96,
      riskTaking: 18,
    },
    keyStrengths: ["Pharmacological chemistry", "Drug interaction verification", "High attention to medical safety"],
    skillsToDevelop: ["Clinical pharmacokinetics", "Biomedical compounding", "Pharmacy inventory governance"],
  },
  "psychologist": {
    family: "healthcare",
    title: "Psychologist",
    category: "Mental Health",
    icon: "Smile",
    description: "Support emotional well-being, conduct psychotherapy, explore behavioral cognitive patterns, and empower clients.",
    dimensions: {
      technical: 30,
      analytical: 76,
      creative: 62,
      business: 46,
      communication: 92,
      leadership: 56,
      research: 82,
      people: 98,
      structured: 72,
      riskTaking: 32,
    },
    keyStrengths: ["Empathetic non-judgmental listening", "Cognitive behavioral therapy (CBT)", "Human behavioral insight"],
    skillsToDevelop: ["Psychometric test administration", "Specialized trauma care methodologies", "Clinical research publishing"],
  },

  // ── Law & Public Service ────────────────────────────────────
  "lawyer": {
    family: "legal",
    title: "Corporate Lawyer",
    category: "Legal",
    icon: "Scale",
    description: "Counsel corporations on governance, regulatory compliance, contract drafting, mergers, and legal advocacy.",
    dimensions: {
      technical: 34,
      analytical: 92,
      creative: 46,
      business: 86,
      communication: 95,
      leadership: 78,
      research: 88,
      people: 62,
      structured: 94,
      riskTaking: 45,
    },
    keyStrengths: ["Contractual precision & drafting", "Adversarial negotiation & persuasion", "Statutory interpretation"],
    skillsToDevelop: ["International commercial arbitration", "Intellectual property technology patents", "Antitrust regulation"],
  },
  "civil-services": {
    family: "legal",
    title: "Civil Services (IAS / IPS)",
    category: "Government & Public Service",
    icon: "ShieldAlert",
    description: "Administer public districts, enforce law and order, implement government welfare, and lead civil governance.",
    dimensions: {
      technical: 40,
      analytical: 84,
      creative: 48,
      business: 72,
      communication: 90,
      leadership: 96,
      research: 76,
      people: 88,
      structured: 92,
      riskTaking: 52,
    },
    keyStrengths: ["Public policy execution", "Crisis management under pressure", "Administrative authority & leadership"],
    skillsToDevelop: ["Public finance budgeting", "E-governance digital transformation", "Disaster response logistics"],
  },
  "army-officer": {
    family: "legal",
    title: "Army Officer",
    category: "Government & Defence",
    icon: "Award",
    description: "Lead armed forces personnel, execute tactical operations, maintain national defense, and embody disciplined command.",
    dimensions: {
      technical: 58,
      analytical: 74,
      creative: 40,
      business: 45,
      communication: 78,
      leadership: 98,
      research: 52,
      people: 75,
      structured: 98,
      riskTaking: 78,
    },
    keyStrengths: ["Supreme operational discipline", "Tactical battlefield strategy", "High-stress situational leadership"],
    skillsToDevelop: ["Modern defense technology & drone systems", "Strategic geopolitical intelligence", "Advanced logistics"],
  },

  // ── Core Engineering ────────────────────────────────────────
  "civil-engineer": {
    family: "engineering",
    title: "Civil Engineer",
    category: "Engineering",
    icon: "HardHat",
    description: "Plan, construct, and oversee municipal bridges, roadways, dams, and modern urban infrastructure projects.",
    dimensions: {
      technical: 78,
      analytical: 84,
      creative: 55,
      business: 60,
      communication: 64,
      leadership: 68,
      research: 60,
      people: 48,
      structured: 92,
      riskTaking: 38,
    },
    keyStrengths: ["Structural physics calculations", "On-site construction management", "Quality material testing"],
    skillsToDevelop: ["AutoCAD & Civil 3D software", "Geotechnical soil testing", "Smart city sustainable design"],
  },
  "mechanical-engineer": {
    family: "engineering",
    title: "Mechanical Engineer",
    category: "Engineering",
    icon: "Cog",
    description: "Design mechanical machinery, thermal engines, robotic automation, and manufacturing tooling.",
    dimensions: {
      technical: 86,
      analytical: 88,
      creative: 62,
      business: 52,
      communication: 58,
      leadership: 55,
      research: 68,
      people: 36,
      structured: 88,
      riskTaking: 42,
    },
    keyStrengths: ["Thermodynamics & fluid mechanics", "CAD manufacturing modeling", "Robotic kinematics"],
    skillsToDevelop: ["Finite Element Analysis (FEA)", "Additive manufacturing (3D printing)", "Mechatronics integration"],
  },

  // ── Education & Social Sciences ─────────────────────────────
  "teacher": {
    family: "education",
    title: "Teacher / Educator",
    category: "Education",
    icon: "GraduationCap",
    description: "Inspire, teach, and mentor students through structured curriculum design, pedagogical clarity, and patience.",
    dimensions: {
      technical: 32,
      analytical: 64,
      creative: 72,
      business: 36,
      communication: 95,
      leadership: 78,
      research: 72,
      people: 96,
      structured: 84,
      riskTaking: 30,
    },
    keyStrengths: ["Pedagogical simplification", "Student inspiration & empathy", "Patience and classroom leadership"],
    skillsToDevelop: ["Interactive digital learning tools", "Personalized educational assessment", "Special educational needs adaptations"],
  },
  "ed-tech": {
    family: "education",
    title: "Ed-Tech / Online Educator",
    category: "Education & Technology",
    icon: "MonitorPlay",
    description: "Create interactive digital courses, scalable learning platforms, video tutorials, and modern educational cohorts.",
    dimensions: {
      technical: 62,
      analytical: 70,
      creative: 82,
      business: 75,
      communication: 94,
      leadership: 72,
      research: 68,
      people: 88,
      structured: 70,
      riskTaking: 62,
    },
    keyStrengths: ["Engaging video lesson delivery", "Curriculum structure for remote learners", "Community cohort facilitation"],
    skillsToDevelop: ["LMS architecture & analytics", "Gamified learning mechanics", "High-retention student workflows"],
  },
  "social-worker": {
    family: "social",
    title: "Social Worker / NGO",
    category: "Social Sciences",
    icon: "HeartHandshake",
    description: "Empower marginalized communities, provide social casework, lead humanitarian relief, and advocate for human rights.",
    dimensions: {
      technical: 22,
      analytical: 58,
      creative: 55,
      business: 50,
      communication: 90,
      leadership: 76,
      research: 65,
      people: 99,
      structured: 70,
      riskTaking: 48,
    },
    keyStrengths: ["Unconditional human empathy", "Grassroots community mobilization", "Trauma and crisis support"],
    skillsToDevelop: ["Grant proposal writing", "Non-profit fiscal governance", "Sociological field research"],
  },

  // ── Science & Research ──────────────────────────────────────
  "biotechnologist": {
    family: "science",
    title: "Biotechnologist",
    category: "Science & Research",
    icon: "Dna",
    description: "Engineer biological organisms, genetic therapies, vaccine formulations, and advanced agricultural improvements.",
    dimensions: {
      technical: 74,
      analytical: 92,
      creative: 55,
      business: 52,
      communication: 60,
      leadership: 44,
      research: 96,
      people: 42,
      structured: 88,
      riskTaking: 45,
    },
    keyStrengths: ["Molecular genetics & assay testing", "Cell culture laboratory rigor", "Scientific hypothesis validation"],
    skillsToDevelop: ["CRISPR gene editing techniques", "Bioinformatics Python packages", "Biopharmaceutical clinical trials"],
  },
  "environmental-scientist": {
    family: "science",
    title: "Environmental Scientist",
    category: "Science & Environment",
    icon: "Leaf",
    description: "Analyze ecological balance, monitor pollution levels, assess climate impact, and champion environmental sustainability.",
    dimensions: {
      technical: 62,
      analytical: 88,
      creative: 50,
      business: 54,
      communication: 74,
      leadership: 55,
      research: 94,
      people: 60,
      structured: 82,
      riskTaking: 40,
    },
    keyStrengths: ["Environmental impact assessment", "Ecological field sampling", "Climate data analysis"],
    skillsToDevelop: ["GIS spatial mapping software", "Carbon footprint auditing", "Environmental compliance policy"],
  },

  // ── Health & Wellness ───────────────────────────────────────
  "nutritionist": {
    family: "wellness",
    title: "Nutritionist / Dietitian",
    category: "Health & Wellness",
    icon: "Apple",
    description: "Create personalized dietary protocols, optimize metabolic health, manage clinical nutritional therapies, and coach lifestyle wellness.",
    dimensions: {
      technical: 40,
      analytical: 74,
      creative: 58,
      business: 58,
      communication: 86,
      leadership: 55,
      research: 76,
      people: 92,
      structured: 82,
      riskTaking: 30,
    },
    keyStrengths: ["Nutritional biochemistry", "Personalized diet coaching", "Patient empathy and motivation"],
    skillsToDevelop: ["Sports nutrition periodization", "Gut microbiome analysis", "Clinical dietetics documentation"],
  },
  "fitness-trainer": {
    family: "wellness",
    title: "Fitness Trainer / Sports Coach",
    category: "Health & Wellness",
    icon: "Dumbbell",
    description: "Coach athletic performance, design strength conditioning regimens, correct movement patterns, and build physical resilience.",
    dimensions: {
      technical: 42,
      analytical: 62,
      creative: 60,
      business: 64,
      communication: 88,
      leadership: 85,
      research: 52,
      people: 90,
      structured: 78,
      riskTaking: 45,
    },
    keyStrengths: ["Biomechanical form coaching", "Energetic team motivation", "Progressive overload programming"],
    skillsToDevelop: ["Athletic recovery science", "Kinesiology injury prevention", "Personal training business marketing"],
  },

  // ── Hospitality & Aviation ──────────────────────────────────
  "pilot": {
    family: "hospitality",
    title: "Commercial Pilot",
    category: "Aviation & Transport",
    icon: "Plane",
    description: "Navigate passenger and cargo aircraft safely across global airspace, managing flight instruments, weather, and cockpit crew.",
    dimensions: {
      technical: 86,
      analytical: 84,
      creative: 30,
      business: 40,
      communication: 82,
      leadership: 88,
      research: 52,
      people: 55,
      structured: 99,
      riskTaking: 45,
    },
    keyStrengths: ["High-speed spatial decision making", "Avionics instrument mastery", "Uncompromising safety checklists"],
    skillsToDevelop: ["Advanced instrument flight rating (IFR)", "Multi-crew cockpit resource management", "Adverse weather navigation"],
  },
  "hotel-management": {
    family: "hospitality",
    title: "Hotel Management / Hospitality",
    category: "Business & Hospitality",
    icon: "Hotel",
    description: "Oversee luxury guest experiences, hotel operations, culinary services, revenue management, and hospitality teams.",
    dimensions: {
      technical: 32,
      analytical: 65,
      creative: 68,
      business: 85,
      communication: 92,
      leadership: 82,
      research: 42,
      people: 94,
      structured: 84,
      riskTaking: 46,
    },
    keyStrengths: ["Luxury customer service excellence", "Front-of-house operations", "Team morale and leadership"],
    skillsToDevelop: ["Hotel revenue & yield management", "Hospitality property management systems (PMS)", "Food & beverage cost control"],
  },
  "event-manager": {
    family: "hospitality",
    title: "Event Manager",
    category: "Business & Hospitality",
    icon: "CalendarCheck",
    description: "Orchestrate large-scale conferences, concerts, corporate summits, and weddings with meticulous production planning.",
    dimensions: {
      technical: 40,
      analytical: 68,
      creative: 85,
      business: 82,
      communication: 94,
      leadership: 86,
      research: 50,
      people: 88,
      structured: 86,
      riskTaking: 62,
    },
    keyStrengths: ["Live event coordination under pressure", "Creative experiential design", "Vendor budget negotiation"],
    skillsToDevelop: ["Audio-visual stage production logistics", "Crowd safety risk assessment", "Corporate sponsor acquisition"],
  },
};

/**
 * Helper to dynamically generate a calibrated dimension profile for any newly added
 * or custom course in MongoDB that is not in the predefined matrix above.
 * Ensures that if a new roadmap is published by an admin, it becomes instantly eligible!
 */
export const inferCourseProfile = (course = {}) => {
  const category = (course.category || "").toLowerCase();
  const title = (course.title || "").toLowerCase();
  const skills = (course.skills || []).map((s) => s.toLowerCase());

  let family = "technology";
  const dims = {
    technical: 50,
    analytical: 50,
    creative: 50,
    business: 50,
    communication: 50,
    leadership: 50,
    research: 50,
    people: 50,
    structured: 50,
    riskTaking: 50,
  };

  if (category.includes("tech") || category.includes("code") || title.includes("developer")) {
    family = "technology";
    dims.technical = 85;
    dims.analytical = 80;
    dims.structured = 75;
  } else if (category.includes("data") || title.includes("analyst") || title.includes("data")) {
    family = "data";
    dims.analytical = 90;
    dims.research = 82;
    dims.technical = 75;
  } else if (category.includes("design") || category.includes("creative") || title.includes("designer")) {
    family = "design";
    dims.creative = 92;
    dims.communication = 75;
    dims.people = 70;
  } else if (category.includes("business") || category.includes("manage") || title.includes("manager")) {
    family = "business";
    dims.business = 90;
    dims.leadership = 85;
    dims.communication = 80;
  } else if (category.includes("health") || category.includes("med") || title.includes("doctor")) {
    family = "healthcare";
    dims.people = 92;
    dims.structured = 85;
    dims.analytical = 78;
  } else if (category.includes("finance") || category.includes("account")) {
    family = "finance";
    dims.analytical = 90;
    dims.structured = 90;
    dims.business = 85;
  } else if (category.includes("market")) {
    family = "marketing";
    dims.communication = 88;
    dims.business = 84;
    dims.creative = 80;
  } else if (category.includes("media")) {
    family = "media";
    dims.creative = 88;
    dims.communication = 92;
    dims.riskTaking = 70;
  }

  // Adjust for skills
  if (skills.some((s) => s.includes("code") || s.includes("programming") || s.includes("python"))) {
    dims.technical = Math.min(95, dims.technical + 15);
  }
  if (skills.some((s) => s.includes("lead") || s.includes("management"))) {
    dims.leadership = Math.min(95, dims.leadership + 15);
  }
  if (skills.some((s) => s.includes("design") || s.includes("art"))) {
    dims.creative = Math.min(95, dims.creative + 15);
  }

  return {
    family,
    title: course.title,
    category: course.category,
    icon: course.icon || "Briefcase",
    description: course.description || `Master the career roadmap for ${course.title}.`,
    dimensions: dims,
    keyStrengths: course.skills?.slice(0, 3) || ["Professional competence", "Problem solving"],
    skillsToDevelop: ["Foundational domain concepts", "Practical project implementation"],
  };
};
